add "-O1 -disable-llvm-optzns"
coderrect-inc/OpenRace pull request #103
Opened 2021-05-06 23:20 UTC by PeimingLiu

This will keep the IR unoptimized but at the same time all the metadata for optimization will be kept

2021-05-07 15:06 UTC, BradSwain requested changes
The following files should be removed:
- tests/data/integration/dataracebench/ll/logs/log.current
- tests/data/integration/dataracebench/ll/modified.ll
- tests/data/integration/dataracebench/ll/o1.ll
- tests/data/integration/dataracebench/ll/output.txt

We should also figure out why the tests crash and update the Makefiles that build the other tests to include these flags as well.

2021-05-07 15:06 UTC, BradSwain commented on tests/data/integration/dataracebench/ll/logs/log.current
> +17:43:50 [debug] [racedetect] [Log.cpp:46] Logging configs. level=1, logFolder=logs, logFile=log.current, enableTerminal=false, enableFile=true
This file should be deleted

2021-05-07 15:12 UTC, BradSwain commented
The crash is caused by an unrecognized `__kmpc_*` call in DRB011.

The call is to a variant of `__kmpc_static_for_init` (`__kmpc_for_static_init_4u`).

This is already supported in  #99 so once that PR is merged the crash should go away.

2021-05-10 23:35 UTC, PeimingLiu commented on tests/data/integration/dataracebench/ll/logs/log.current
> +17:43:50 [debug] [racedetect] [Log.cpp:46] Logging configs. level=1, logFolder=logs, logFile=log.current, enableTerminal=false, enableFile=true
removed

2021-05-10 23:41 UTC, BradSwain commented
I still need to add these flags to our other tests. I have mostly done it locally but have not had time to finish and push to this branch

2021-05-11 22:05 UTC, BradSwain commented
I added a top level Makefile so that:
 - the same flags are used to build all test files
 - we can check the right compiler version is used
 - only need to run make in one place to generate test data

As a downside/side effect all the .ll files are now located side  by side with the source files.

@funemy Can you check to make sure I didn't miss anything? If it looks good feel free to merge.

2021-05-12 03:39 UTC, merged