support DRB053, and DRB054
coderrect-inc/OpenRace pull request #104
Opened 2021-05-10 23:39 UTC by PeimingLiu

In progress, not yet fully tested.

2021-05-11 13:49 UTC, BradSwain requested changes

2021-05-11 18:00 UTC, PeimingLiu commented
DRB054 now works

2021-05-11 18:01 UTC, PeimingLiu commented on src/Analysis/OpenMPAnalysis.cpp
> +  static OpenMPLoopManager ompManager(FAM, targetFun);
This is static to cache the result for the same function, otherwise I can reanalyzed the same function everytime a call to array index analysis

2021-05-11 23:02 UTC, PeimingLiu commented
@BradSwain 

DRB063 and DRB064 are now supported.

2021-05-19 22:08 UTC, BradSwain requested changes
One general comment, the static functions need to be converted to anonymous namespace.

2021-05-19 22:08 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  void rebuildWith(AnalysisManager<Function> &FAM, Function &F);
Is this called anywhere?

2021-05-19 22:26 UTC, PeimingLiu commented on src/IR/Builder.cpp
> +#include <llvm/Analysis/ScopedNoAliasAA.h>
To make Inter-procedural constant propagation easier

2021-05-19 22:26 UTC, PeimingLiu commented on src/PreProcessing/PreProcessing.cpp
> +  markOMPDebugAlwaysInline(module);
To make inter-procedural constant propagation easier

2021-05-19 22:36 UTC, PeimingLiu commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (omp1 == scev1 && omp2 == scev2) {
No, it is to checkout the openmp loop does not contains a nested loop.

if it contains nested loop
scev = {()<omp.loop>}<outloop>
omp = ()<omp.loop>

2021-05-20 01:53 UTC, funemy commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (omp1 == scev1 && omp2 == scev2) {
> No, it is to checkout the openmp loop does not contains a nested loop.
> 
> if it contains nested loop
> scev = {()<omp.loop>}<outloop>
> omp = ()<omp.loop>

So the \<outloop\> will be removed by `stripSCEVBaseAddr`?
Is \<outloop\> just a `%base`?

2021-05-20 03:40 UTC, PeimingLiu commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (omp1 == scev1 && omp2 == scev2) {
No, stripSCEVBassAddr is to strip the base address
 like %base + {SCEV_REC}

`omp` is the scalar evolution expression just for the openmp loop.
However, if the openmp loop has nested (inner loop)
`scev` contains not only the openmp loop information but also the inner loop expression.
by comparing these two, we can determine whether there is a nested loop in the openmp loop

However, I currently only handle two-level nested loop

2021-05-20 03:42 UTC, PeimingLiu commented on src/Analysis/OpenMPAnalysis.cpp
> +  void rebuildWith(AnalysisManager<Function> &FAM, Function &F);
No, I will delete it.

It is used when the OMPLoopManager is static, but since you suggested to make it non-static, this code is useless now

2021-05-20 03:52 UTC, funemy commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (omp1 == scev1 && omp2 == scev2) {
Oh, I see the point!
The inner-most loop will present in the outer-most part of SCEV.
So if `omp == scev`, it means there's no nested loop inside openmp loop.
Is that right?

2021-05-20 03:56 UTC, funemy commented on src/Analysis/OpenMPAnalysis.cpp
> +      if (ompManager.isOMPForLoop(addRec->getLoop())) {
worth commenting here we only look for double-nested loop at most?

2021-05-20 18:29 UTC, BradSwain commented on src/PreProcessing/PreProcessing.cpp
> +  fpm.addPass(llvm::SROA());
Fixed in #116

2021-05-20 18:29 UTC, BradSwain commented on src/PreProcessing/PreProcessing.cpp
> +  markOMPDebugAlwaysInline(module);
Fixed in #116

2021-05-20 18:29 UTC, BradSwain commented on src/PreProcessing/PreProcessing.cpp
> +  //fpm.addPass(CanonicalizeGEPPass());
Fixed in #116

2021-05-20 18:29 UTC, BradSwain commented on src/PreProcessing/PreProcessing.cpp
> +  fpmPost.addPass(CanonicalizeGEPPass());
Fixed in #116

2021-05-20 18:30 UTC, BradSwain commented on src/IR/Builder.cpp
> +#include <llvm/Analysis/ScopedNoAliasAA.h>
Fixed in #116

2021-05-20 18:31 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +//
Fixed in #116

2021-05-20 18:32 UTC, BradSwain commented on src/Trace/Event.h
> +  [[nodiscard]] const llvm::Function *getFunction() const { return getIRInst()->getInst()->getFunction(); }
Fixed in #116

2021-05-20 18:35 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.h
> +struct LegacyOMPConstantPropPass : public llvm::ModulePass {
Fixed in #116

2021-05-20 18:41 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +  if (F.getName().startswith(".omp_outlined.")) {
Fixed in #116

2021-05-20 18:42 UTC, BradSwain commented on src/PreProcessing/PreProcessing.cpp
> +    if (!F.isDeclaration() && F.getName().startswith(".omp_outlined._debug")) {
Fixed in #116

2021-05-20 18:46 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
>    // TODO: get rid of const cast? Also does FAM cache these results (I think it does?)
Fixed in #116

2021-05-20 18:48 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +              return true;
Fixed in #116

2021-05-20 18:49 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  auto &LI = FAM.getResult<LoopAnalysis>(targetFun);
Fixed in #116

2021-05-20 19:38 UTC, BradSwain commented on src/RaceDetect.cpp
> +    if (write->getFunction() == other->getFunction()) {
Fixed in #116

2021-05-20 19:45 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +    while (LocalChange) {
Addressed in #116

2021-05-26 17:59 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +static bool intraConstantProp(Function &F, const TargetLibraryInfo &TLI) {
Addressed in #135

2021-05-26 18:06 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +static bool PropagateConstantsIntoArguments(Function &F, const DominatorTree &DT, const TargetLibraryInfo &TLI) {
Addressed in #135

2021-05-26 18:18 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +        ArgumentConstants[i].second = true;
Addressed in #135

2021-05-26 18:21 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +    if (ArgumentConstants[i].second || AI->use_empty() || AI->hasInAllocaAttr() ||
Added fixme comment in #135

2021-05-26 18:21 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +  Function::arg_iterator AI = F.arg_begin();
Addressed in #135

2021-05-26 18:35 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +static StoreInst *findUniqueDominatedStoreDef(Value *V, const Instruction *I, const DominatorTree &DT) {
Addressed in #135

2021-05-26 18:35 UTC, BradSwain commented on src/PreProcessing/Passes/OMPConstantPropPass.cpp
> +  // special case, the omp_outlined function calls use a pointer but only reads it
Addressed in #135

2021-05-26 18:35 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  // the rewriter here move the bit extension operation into the deepest scopy
Addressed in #135

2021-05-26 18:41 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  // strip off the scev
Addressed in #135

2021-05-26 18:41 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +static const SCEVAddRecExpr *getOMPLoopSCEV(const llvm::SCEV *root, const OpenMPLoopManager &ompManager) {
Addressed in #135

2021-05-26 18:41 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (!omp1 && !omp2) {
Addressed in #135

2021-05-26 18:46 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +      auto bounds = ompManager.resolveOMPLoopBound(initForCall);
Addressed in #135

2021-05-26 18:46 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  void rebuildWith(AnalysisManager<Function> &FAM, Function &F);
Addressed in #135

2021-05-26 18:48 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (std::all_of(gaps.begin(), gaps.end(), [](const SCEV *expr)->bool {
fixme comment added in #135

2021-05-26 18:50 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  auto step = root->getOperand(1);
Addressed in #135

2021-05-26 18:51 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +        if (std::max(lowerBound, upperBound) < (distance / loopStep)) {
fixme added in #135

2021-05-26 22:34 UTC, funemy commented on src/PreProcessing/Passes/OMPConstantPropPass.h
> +//
do we still want to keep this three lines?

2021-05-26 22:37 UTC, funemy approved these changes

2021-05-26 22:37 UTC, BradSwain approved these changes

2021-05-26 22:37 UTC, merged