Fix the issue Support OpenMP critical #92
coderrect-inc/OpenRace pull request #112
Opened 2021-05-18 14:44 UTC by jedishao23

Treat the openMP critical as a lock.

2021-05-18 15:01 UTC, BradSwain commented
Hi @jedishao23 thanks for the PR. Looks very high quality!
I will try to do a full review later today and get this merged.

2021-05-18 15:01 UTC, BradSwain commented
closes #92

2021-05-18 16:30 UTC, BradSwain requested changes
Look great! Just two small changes adding some comments about the OpenMP API's modeled and I think it is ready to be merged.

2021-05-18 16:30 UTC, BradSwain commented on src/IR/IRImpls.h
> +  const unsigned int criticalEntryOffset = 2;
Can you add a comment here describing the kmpc_critical API and linking to the functio in LLVM's github project?

You can use the comment for OpenMP fork as a template

https://github.com/coderrect-inc/OpenRace/blob/328fe090a12055e4e2731557b1ea1cc32ede8776/src/IR/IRImpls.h#L122-L129

2021-05-18 16:30 UTC, BradSwain commented on src/IR/IRImpls.h
> +  const unsigned int criticalEndOffset = 2;
Can you add a comment here describing the kmpc_end_critical API and linking to the function in LLVM's github project?

You can use the comment for OpenMP fork as a template.

https://github.com/coderrect-inc/OpenRace/blob/328fe090a12055e4e2731557b1ea1cc32ede8776/src/IR/IRImpls.h#L122-L129

2021-05-18 22:40 UTC, funemy commented on src/IR/IRImpls.h
> +  const unsigned int criticalEntryOffset = 2;
I suggest we should rename `criticalEntryOffset`.

The offset seems to denote the actual lock object being acquired or just a identify for the critical section?
(according to the reference https://openmp.llvm.org/Reference.pdf)

In that case, we should name it `identifyOffset` or `lockOffset`.

2021-05-18 22:40 UTC, funemy commented on src/IR/IRImpls.h
> +  const unsigned int criticalEndOffset = 2;
Same as my comment above. We should rename `criticalEndOffset`

2021-05-19 02:07 UTC, jedishao23 commented on src/IR/IRImpls.h
> +  const unsigned int criticalEndOffset = 2;
OK, I'll rename them and add comments.

2021-05-19 02:44 UTC, funemy reviewed
LGTM now, I'll let @BradSwain approve it

2021-05-19 13:59 UTC, BradSwain approved these changes

2021-05-19 14:01 UTC, BradSwain commented
Thanks @jedishao23 looks good to me. Thanks again for the high quality contribution!

2021-05-19 14:01 UTC, merged