Added efficient binary search on loop range search
coderrect-inc/OpenRace pull request #127
Opened 2021-05-25 03:22 UTC by tanzircoderrect

The current version uses a linear search on the loop ranges. These loop ranges are disjoint and created in the order of when their ends are encountered. As a result, these ranges are already sorted, which supports binary search. Therefore, all the linear searches are replaced by binary search function (i.e., lower_bound). A comparator RegionLessThan was added in the .h that compares two ranges based on the "end" value. This makes lower_bound() put an eventID in the right range if it already exists or in a higher range, which means eventID does not belong.

2021-05-25 14:58 UTC, BradSwain requested changes
Looks great! Just a couple of small changes requested and then it looks good to me.

2021-05-25 14:58 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.h
> +
Can this be made into a function and put inside of an anonymous namespace in OpenMPAnalysis.cpp?

```cpp
bool regionEndLessThan(const Region& region1, const Region& region2) { return region1.end < region2.end; }
```

2021-05-25 14:58 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  auto it = lower_bound (loopRegions.begin(), loopRegions.end(), temp, RegionLessThan());
Can the `temp` passed to `lower_bound` here be replaced with `Region(eid, eid)` directly to match the other calls to lower_bound?

2021-05-26 17:41 UTC, tanzircoderrect commented on src/Analysis/OpenMPAnalysis.cpp
> +  auto it = lower_bound (loopRegions.begin(), loopRegions.end(), temp, RegionLessThan());
Done

2021-05-26 19:09 UTC, BradSwain approved these changes

2021-05-26 19:09 UTC, merged