OpenMP master (implement #91)
coderrect-inc/OpenRace pull request #128
Opened 2021-05-25 11:35 UTC by addison-coderrect

This PR implements #91 and associated testing.

2021-05-25 18:41 UTC, BradSwain requested changes
LGTM after one small update to a comment. @funemy  wnat to take a second look?

2021-05-25 18:41 UTC, BradSwain commented on src/RaceDetect.cpp
>        // Certain omp blocks cannot race with themselves
Update this comment to add a little more detail. Single blocks cannot race with themselves, Master blocks cannot race with other master blocks.

2021-05-25 21:18 UTC, addison-coderrect commented
Adding a targeted test to check compatibility with: https://github.com/coderrect-inc/OpenRace/issues/91#issuecomment-848041806

2021-05-26 13:10 UTC, BradSwain approved these changes

2021-05-26 13:11 UTC, merged