Implement sections, but better
coderrect-inc/OpenRace pull request #156
Opened 2021-06-03 21:46 UTC by addison-coderrect

Closes #114, huzzah!

2021-06-03 21:53 UTC, BradSwain requested changes

2021-06-03 21:53 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.h
> +  static bool inCompatibleSections(const Event* event1, const Event* event2);
a nitpick, but I prefer a different name. `inCompatibleSections` sounds too close to "incompatible sections" which would have the opposite meaning.

2021-06-03 21:53 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +      }
Why do we end traversal at this block label?

2021-06-03 21:55 UTC, addison-coderrect commented on src/Analysis/OpenMPAnalysis.cpp
> +      }
Because the parallel for actually "iterates" and goes back to the body; if we follow descendants through the body, all sections contain all descendants.

2021-06-03 22:11 UTC, BradSwain approved these changes

2021-06-03 22:15 UTC, merged

2021-06-04 04:49 UTC, funemy commented on src/Analysis/OpenMPAnalysis.cpp
> +      }
Why not using `omp.sections.exit` as the end signal? Seems more precise to me.

I'm looking at [DRB023](https://github.com/coderrect-inc/OpenRace/blob/develop/tests/data/integration/dataracebench/DRB023-sections1-orig-yes.ll)
And the BB pattern is like
```
         omp.inner.for.cond-------------------|
                  |                           |
         omp.inner.for.body                   |
          /               \                   |
.omp.sections.case  .omp.sections.case1       |
          \               /                   |
         omp.sections.exit                    |
                  |                           |
         omp.inner.for.inc--------------------|
                  |
         omp.inner.for.end
```
If we start with `omp.sections.case` and `omp.sections.case1` and end at `omp.inner.for.body`.
The events in `omp.inner.for.inc` and `omp.inner.for.end` will also be recognized as "events in a section".
Is that right? Did I miss any important logic here?