Fixed issues from before
coderrect-inc/OpenRace pull request #167
Opened 2021-06-07 05:47 UTC by RohanKheraCR

I fixed the issues that were mentioned. For single message printer, the total is supposed to be outside the pragma so a race condition is generated because the other thread can access total.

2021-06-07 14:35 UTC, BradSwain requested changes

2021-06-07 14:35 UTC, BradSwain commented on tests/data/Makefile
> +CXX=/home/brad/coderrect-inc/install/bin/clang++
This change should be removed.

2021-06-07 14:35 UTC, BradSwain commented on tests/data/integration/openmp/master-iteration-counter-no.c
> +    }  while(toobig > 0);
It looks like the indentation is off by one level here.

2021-06-07 14:35 UTC, BradSwain commented on tests/data/integration/openmp/single-message-printer.c
> +        total -= 2;
Are the accesses to total meant to be within the single region?

2021-06-07 14:42 UTC, RohanKheraCR commented on tests/data/integration/openmp/single-message-printer.c
> +        total -= 2;
No, I put them outside so that a race condition could occur if the thread doing work 1 tries to change total while the thread doing work 2 is doing the same (no race condition is generated if total is inside the single region)

2021-06-07 14:44 UTC, BradSwain commented on tests/data/integration/openmp/single-message-printer.c
> +        total -= 2;
Alright sounds good. Can you add a comment to the top of the file describing the expected race?

2021-06-07 16:22 UTC, BradSwain requested changes

2021-06-07 16:22 UTC, BradSwain commented on tests/integration/openmp.test.cpp
>    };
We should also keep the `duplicate-omp-fork.ll` Oracle.

2021-06-07 16:30 UTC, RohanKheraCR commented on tests/integration/openmp.test.cpp
>    };
If I keep that, it does not pass the tests because my repo still shows a race condition for that file, is that alright?

2021-06-08 22:34 UTC, BradSwain approved these changes

2021-06-08 22:34 UTC, merged