Let user specify heuristics: INDIRECT_OPTION and Max_Indirect_Target
coderrect-inc/OpenRace pull request #183
Opened 2021-06-10 16:16 UTC by bz-liu

Let user specify heuristics: `INDIRECT_OPTION` and `Max_Indirect_Target`

2021-06-10 19:40 UTC, BradSwain requested changes

2021-06-10 19:40 UTC, BradSwain commented on src/PointerAnalysis/CMDOptions.cpp
> +unsigned int pta::Max_Indirect_Target = 999;
Just a small change, but can `999` be replaced `std::numeric_limits<unsigned int>::max()`. 
This way by default the max indirect target cap is effectively "off".

I think `#include <limits>` will need to be added as well.

2021-06-10 19:40 UTC, BradSwain commented on src/PointerAnalysis/Models/LanguageModel/ConsGraphBuilder.h
> +
Is there anyway to pass this without relying on `extern`?

2021-06-10 19:40 UTC, BradSwain commented on src/PointerAnalysis/Program/CtxFunction.h
> +
Is there anyway to pass this without relying on `extern`?

2021-06-10 19:40 UTC, BradSwain commented on src/main.cpp
> +  pta::ParseCommandLineOptions(argc, argv);
I don't think we should move the command line option parsing into PTA.

If all the command line options for PTA are added as `llvm::cl` stuff they will be automatically parsed by `llvm::cl::ParseCommandLineOptions`

2021-06-10 19:40 UTC, BradSwain commented on src/PointerAnalysis/Models/LanguageModel/ConsGraphBuilder.h
> +              bool applyLimit = (result == IndirectResolveOption::WITH_LIMIT ? true : false);
What does this change do?

2021-06-10 23:16 UTC, bz-liu commented on src/PointerAnalysis/CMDOptions.cpp
> +unsigned int pta::Max_Indirect_Target = 999;
Then what is `IndirectResolveOption::CRITICAL` represent? In the code it has a comment like: 
```c
enum class IndirectResolveOption {
  SKIP,        // do not add the resolved function to the callgraph
  WITH_LIMIT,  // only add the resolved function to the callgraph iff the
               // indirect call limit is not exceeded.
  CRITICAL,    // make sure the function are inserted to callgraph, even if the
               // limit has been exceeded.
};
```
Then both default `WITH_LIMIT` and `CRITICAL` will be effectively "off"

2021-06-10 23:26 UTC, bz-liu commented on src/PointerAnalysis/Models/LanguageModel/ConsGraphBuilder.h
> +
I googled, did not find a solution. I'm not an c/c++ expert, maybe I googled in a wrong way? I see this `extern` has been used in the pta code, e.g., src/PointerAnalysis/Models/MemoryModel/FieldSensitive/MemBlock.h:25.

2021-06-10 23:27 UTC, bz-liu commented on src/PointerAnalysis/Models/LanguageModel/ConsGraphBuilder.h
> +              bool applyLimit = (result == IndirectResolveOption::WITH_LIMIT ? true : false);
previously, there is no option for `CRITICAL`, the commented-off line is the original code.

2021-06-10 23:28 UTC, bz-liu commented on src/main.cpp
> +  pta::ParseCommandLineOptions(argc, argv);
ok, will update.

2021-06-11 16:47 UTC, BradSwain approved these changes

2021-06-11 16:47 UTC, merged

2021-06-11 16:48 UTC, BradSwain commented
If possible we should try top refactor PTA to pass the configs in explicitly rather than relying on extern `llvm::cl` objects.
But not very high priority, so we can leave that for later.

2021-06-11 16:50 UTC, bz-liu commented
I'll add a TODO in the code.