Added some tests cases for ordered clause
coderrect-inc/OpenRace pull request #214
Opened 2021-06-17 22:28 UTC by RohanKheraCR

2021-06-18 18:45 UTC, BradSwain requested changes
The expected races for these two tests should be added to `tests/integration/openmp.test.cpp`

2021-06-21 15:26 UTC, RohanKheraCR commented
> The expected races for these two tests should be added to `tests/integration/openmp.test.cpp`

Added expected races as comments since the test wont pass until ordered is supported.

2021-06-21 17:01 UTC, BradSwain commented
Ordered should already be supported.

I looked into the failed assertion and it looks like we cannot pass these because we don't handle `__kmpc_dispatch_init_4`.
Can you add a comment to the test oracles saying we need to add support for `__kmpc_dispatch_init` to pass those cases?

2021-06-21 19:14 UTC, BradSwain approved these changes

2021-06-21 19:18 UTC, merged