Update openmp nested lock; add the check of array access; add more debug printout info.
coderrect-inc/OpenRace pull request #223
Opened 2021-06-22 19:16 UTC by bz-liu

Update openmp nested lock; add the check of array access; add more debug printout info.

2021-06-22 19:47 UTC, BradSwain requested changes

2021-06-22 19:47 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  assert(_fromSameParallelRegion(event1, event2) && "events must be in same omp team");
Can the `"events must be in same omp team"` message also be updated.

2021-06-22 19:47 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  auto lastID = std::max(event1->getID(), event2->getID());  // why not start from event?
What does this comment mean?

2021-06-22 19:47 UTC, BradSwain commented on src/RaceDetect.cpp
> +          !ompAnalysis.canIndexOverlap(write, other)) {
I think it is easier to read if the `isArray` checks are moved inside of the `isLoopArrayAccess` function.

2021-06-22 19:59 UTC, bz-liu commented on src/RaceDetect.cpp
> +          !ompAnalysis.canIndexOverlap(write, other)) {
for the current code, this is the only place that uses `isLoopArrayAccess` and `canIndexOverlap`, so move `isArrayAccess` inside is ok. What if in the future we have more uses of `isLoopArrayAccess` and `canIndexOverlap` which are not used together? we need some way to enforce the use of `isArrayAccess` check before calling these two functions, or other array-related functions. Correct me if I'm wrong.

2021-06-22 20:04 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  auto lastID = std::max(event1->getID(), event2->getID());  // why not start from event?
this is used by myself and put in a wrong space, lol. removed.

2021-06-22 20:04 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  assert(_fromSameParallelRegion(event1, event2) && "events must be in same omp team");
updated

2021-06-22 20:41 UTC, bz-liu commented
I still have updates. lol.

2021-06-22 20:45 UTC, BradSwain commented on src/RaceDetect.cpp
> +          !ompAnalysis.canIndexOverlap(write, other)) {
Makes sense to me.

In cases where `A` always needs to be checked  before `B`, maybe we can just Check `A` at the start of `B`.

So if `isArray` always needs to be true before `isLoopArrayAccess` is called, I think it makes sense to move that call inside of `isLoopArrayAccess`.

By the same logic, maybe we should also include a call to `isLoopArrayAccess` inside of `canIndexOverlap`, because `canIndexOverlap` should never be called without checking `isLoopArrayAccess` first.

Do you think that is a good idea to bundle all the required checks into a single function call?

2021-06-22 20:50 UTC, bz-liu commented on src/RaceDetect.cpp
> +          !ompAnalysis.canIndexOverlap(write, other)) {
Agreed. Then we need to check twice `isArray` for the above part of the code. 
Another thing I just found is the name of function `getArrayAccess` in `src/Analysis/OpenMPAnalysis.cpp`: this is more like "get def"/"get getelementptr", not all `getelementptr` is array-related. So, maybe change the name to `getGEP`?

2021-06-22 21:08 UTC, bz-liu commented on src/RaceDetect.cpp
> +          !ompAnalysis.canIndexOverlap(write, other)) {
moved inside.

2021-06-23 00:36 UTC, BradSwain commented on src/RaceDetect.cpp
> +          !ompAnalysis.canIndexOverlap(write, other)) {
Yeah changing name of `getArrayAccess` makes sense to me.

2021-06-23 01:59 UTC, BradSwain approved these changes

2021-06-23 01:59 UTC, BradSwain commented
LGTM. Feel free to merge if everything is ready.

2021-06-23 13:59 UTC, merged

2021-06-23 14:00 UTC, bz-liu commented
#197