Continue with tanzircoderrect:develop to handle omp tasks
coderrect-inc/OpenRace pull request #232
Opened 2021-06-23 19:59 UTC by bz-liu

Continue with tanzircoderrect:develop to handle omp tasks.

2021-06-24 17:10 UTC, BradSwain requested changes

2021-06-24 17:10 UTC, BradSwain commented on src/IR/IRImpls.h
> +    auto taskFunc = taskAllocCall.getArgOperand(5)->stripPointerCasts();
Also try to avoid using unnamed numbers directly in calls.

`taskAllocCall.getArgOperand(5)` -> `taskAllocCall.getArgOperand(taskEntryOffset)`

2021-06-24 17:10 UTC, BradSwain commented on src/IR/IRImpls.h
> +  constexpr static unsigned int threadEntryOffset = 2;
It looks like these constants are unused. If so they should be removed.

2021-06-24 17:10 UTC, BradSwain commented on tests/integration/dataracebench.test.cpp
> +
Is this oracle correct?

I think there should only be one race reported between the write at line 61 and the write at line 63.
I don't think there is a self race on line 61 or line 63.

2021-06-24 17:10 UTC, BradSwain commented on src/PointerAnalysis/Models/MemoryModel/DefaultHeapModel.h
> +    //    return nullptr;
can this be removed?

2021-06-24 17:11 UTC, bz-liu commented on src/IR/Builder.cpp
> +          instructions.push_back(std::make_shared<OpenMPTaskJoin>(taskStart));
I changed this, haven't commit yet. lol

2021-06-24 17:18 UTC, bz-liu commented on tests/integration/dataracebench.test.cpp
> +
it is wrong ... "DRB027-taskdependmissing-orig-yes.c:63:7 DRB027-taskdependmissing-orig-yes.c:66:20" should be removed since there is an implicit join after omp single. Will update this when I can pass this test.

2021-06-24 17:19 UTC, bz-liu commented on tests/integration/dataracebench.test.cpp
> +
self race is because we spawn two threads for omp parallel and then two task threads, in total four threads.

2021-06-24 18:02 UTC, bz-liu commented on src/IR/IRImpls.h
> +  constexpr static unsigned int threadEntryOffset = 2;
they are used in `IRImpls.h`.

2021-06-24 19:12 UTC, BradSwain commented on src/IR/IRImpls.h
> +  constexpr static unsigned int threadEntryOffset = 2;
oh sorry I missed it.

2021-06-24 19:22 UTC, bz-liu commented on src/PointerAnalysis/Models/MemoryModel/DefaultHeapModel.h
> +    //    return nullptr;
removed.

2021-06-24 19:22 UTC, bz-liu commented on src/IR/IRImpls.h
> +    auto taskFunc = taskAllocCall.getArgOperand(5)->stripPointerCasts();
updated.

2021-06-24 19:23 UTC, bz-liu commented on src/IR/IRImpls.h
> +    auto op = inst->getArgOperand(2)->stripPointerCasts();
updated.

2021-06-24 19:25 UTC, bz-liu commented
pass DRB27

2021-06-24 20:11 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +        }
solved by PR #234

2021-07-19 18:40 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.h
> -
The same region on different threads may not have the same size.
    For example, a task spawn inside a single region will only appear on one
    thread. So the single region on the second thread will be shorter by one
    event.

Thread 1
-----------
0: single start
1: task spawn
2: write
3: single end

Thread 2
-----------
0: single start
// task spawn skipped
1: write
2: single end

In the above example the two single regions are different sizes because the task spawn is skipped on the second thread.

2021-07-19 18:40 UTC, BradSwain commented on src/RaceDetect.cpp
> +
Moved this higher up so that if the program crashes during race detection we can still see the program trace

2021-07-19 19:48 UTC, addison-coderrect commented on src/Analysis/HappensBeforeGraph.cpp
> +  if (fork) return fork.value();
if (auto const fork...)?

2021-07-19 19:50 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +  if (fork) return fork.value();
We only store this `fork` to task join events. If `fork != nullptr`, we directly return this stored fork value/event. Otherwise, go find the correct fork.

2021-07-19 22:35 UTC, funemy commented on src/Analysis/HappensBeforeGraph.cpp
> +  if (fork) return fork.value();
I think Addison is suggesting these two lines can be merged into one

2021-07-20 05:37 UTC, funemy requested changes
Kudos for this HUGE change,

A few places can still be improved, see comments

2021-07-20 05:37 UTC, funemy commented on src/Trace/ProgramTrace.h
> +  // record the start of a master
can you add a blank line above?

2021-07-20 05:37 UTC, funemy commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
This is indeed ugly, maybe add a new API in `ForkEvent` that returns a shared_ptr of the IR instead of the raw pointer.

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +// all tasks in state.taskWOJoins should be joined when any of the following occur:
update `taskWOJoins`

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +}
This function doesn't need to exist anymore:
1. `isMasterThread` is not even used
2. it's simple, so just inline it

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +bool handleOpenMPMaster(const CallIR *callIR, TraceBuildState &state, bool isMasterThread) {
From this type signature, we really should also put `isMasterThread` in the `TraceBuildState`

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +bool handleOMPEvents(const CallIR *callIR, TraceBuildState &state, bool isMasterThread) {
Seems like `handleOpenMPMaster` and `handleOpenMPSinlge` are both simple enough to be inlined here.

Just use a switch.

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +  bool isFork = callstack.isEmpty();
can be deleted

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +  auto const &irFunc = summary->instructions;
`irFunc` is not a informative name, maybe just call it `summary`?

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +      // Only put omp task forks on master thread if spawned in single region
"Only put omp task forks on master thread if spawned in single region"
->
"if spawned in single region, put omp task forks on master thread only"
reads clearer.

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +      auto forkEvent = static_cast<const ForkEvent *>(event);
Use llvm cast

2021-07-20 05:37 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +      // check if need to insert joins for tasks
Make this comment more specific

2021-07-20 14:18 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +// recursively find the root spawnsite (from #pragma omp parallel) for this event
"merely the closest(innermost) OpenMPFork" -> Good definition! Will update.

2021-07-20 14:32 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (parent->getIRInst()->type == IR::Type::OpenMPTask) {
Good question! because this only valid when the event is from threads spawned by `OpenMPTask` (or maybe also `OpenMPForkTeams` later if we also need such checks). 

For other cases (e.g., events from threads spawned by `OpenMPFork`), if there exists such a region, the region must be in the same thread, not parent thread. If we remove the check, we will get wrong/null regions for the other cases.

2021-07-20 14:33 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  }
The same reason as above: this only valid when the event is from threads spawned by `OpenMPTask`. If we cannot find such a region (when `regions` is empty), there does not exist such a region for the event or our built thread trace is wrong.

2021-07-20 14:33 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +// (event1 always has the thread trace with full irs)
Good point, will do.

2021-07-20 14:34 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  // get omp block contains the event
Good point, will update.

2021-07-20 14:34 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (!region1 || !region2) {  // should have block
Good point, will update.

2021-07-20 14:34 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  // auto const loopRegions = ;
lol, will do.

2021-07-20 14:35 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +// only use this when no tasks in single block
lol, will remove

2021-07-20 14:35 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (event->getIRInst()->type == race::IR::Type::OpenMPReduce) {
will update!

2021-07-20 14:36 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.h
> +  // Return true of the other region is the same region in the IR
lol, typo.

2021-07-20 14:37 UTC, bz-liu commented on src/IR/Builder.cpp
> +          summary.instructions.push_back(taskStart);
yes and will do.

2021-07-20 14:38 UTC, bz-liu commented on src/IR/Builder.cpp
> +          auto ompFork = std::make_shared<OpenMPFork>(callInst, true);
Good point.

2021-07-20 14:41 UTC, bz-liu commented on src/IR/Builder.cpp
> +  auto sharedSummary = std::make_shared<FunctionSummary>(summary);
@BradSwain ?

2021-07-20 14:41 UTC, bz-liu commented on src/IR/Builder.h
> +};
@BradSwain ?

2021-07-20 14:42 UTC, bz-liu commented on src/IR/IR.h
> +    OpenMPTask,
@BradSwain

2021-07-20 14:42 UTC, bz-liu commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
Yes

2021-07-20 14:43 UTC, bz-liu commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
@BradSwain

2021-07-20 14:44 UTC, bz-liu commented on src/IR/IRImpls.h
> +  constexpr static unsigned int taskEntryOffset = 5;
Good point, will update

2021-07-20 14:45 UTC, bz-liu commented on src/IR/IRImpls.h
> +    llvm::CallSite taskAllocCall(llvm::cast<llvm::Instruction>(op));
@BradSwain Tanzir wrote the class?

2021-07-20 14:47 UTC, bz-liu commented on src/IR/IRImpls.h
> +    return llvm::cast<llvm::Function>(taskFunc);
seems like no. lol.

2021-07-20 14:49 UTC, bz-liu commented on src/IR/IRImpls.h
> +  explicit OpenMPTaskJoin(const std::shared_ptr<const OpenMPTask> _task) : JoinIR(Type::OpenMPTaskJoin), task(_task) {}
Previously, to avoid the compiler warnings `-Wshadow # warn the user if a variable declaration shadows one from a parent context`. Now, since the warning is turned off, we can change `_task` to `task`.

2021-07-20 14:52 UTC, bz-liu commented on src/IR/IRImpls.h
> +using OpenMPTaskAlloc = CallIRImpl<IR::Type::OpenMPTaskAlloc>;
Yes, in `genenrateFunctionSummary`.

2021-07-20 14:52 UTC, funemy commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
where?

2021-07-20 14:52 UTC, bz-liu commented on src/LanguageModel/OpenMP.h
> +}
lol, yes

2021-07-20 14:54 UTC, bz-liu commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
@BradSwain  lol

2021-07-20 14:55 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +bool handleOMPEvents(const CallIR *callIR, TraceBuildState &state, bool isMasterThread) {
@BradSwain ?

2021-07-20 14:56 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +  auto const &irFunc = summary->instructions;
maybe `irs`, we already have `summary`.

2021-07-20 14:58 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +  auto const &irFunc = summary->instructions;
once you change the class `FunctionSummary` back to just a vector, you don't need line 143. So we can use `summary`

2021-07-20 15:00 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +  auto const &irFunc = summary->instructions;
Oh, yes, the struct has changed.

2021-07-20 15:02 UTC, bz-liu commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
in function `generateFunctionSummary`, but seems not an important use, just to mark this is a task allocation.

2021-07-20 15:10 UTC, funemy commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (parent->getIRInst()->type == IR::Type::OpenMPTask) {
I see, this makes sense.

Can you add comments here, in case we need to revisit this in the future (like, for `OpenMPForkTeams`)

2021-07-20 15:11 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (parent->getIRInst()->type == IR::Type::OpenMPTask) {
will do!

2021-07-20 15:17 UTC, funemy commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
Oh, I wasn't being very clear.
Yes I see it's directly used in `generateFunctionSummary`.
But this IR is not useful in building thread trace nor the analysis.
So we technically don't need this IR? If so, I think we should remove it

2021-07-20 15:20 UTC, bz-liu commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
>But this IR is not useful in building thread trace nor the analysis.

Yes 

>So we technically don't need this IR?

I think so, I'll see if there's any error after removing this IR.

2021-07-20 15:36 UTC, BradSwain commented on src/IR/Builder.h
> +};
I can make this change

2021-07-20 15:36 UTC, BradSwain commented on src/IR/IR.h
> +    OpenMPTask,
I can make this change

2021-07-20 15:37 UTC, BradSwain commented on src/IR/Builder.cpp
> +  auto sharedSummary = std::make_shared<FunctionSummary>(summary);
I can make this change

2021-07-20 15:39 UTC, BradSwain commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
I can make this change

2021-07-20 15:39 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +}
I can make this change

2021-07-20 16:10 UTC, BradSwain commented on src/IR/IRImpls.h
> +    llvm::CallSite taskAllocCall(llvm::cast<llvm::Instruction>(op));
updated

2021-07-20 16:11 UTC, BradSwain commented on src/IR/IRImpls.h
> +  constexpr static unsigned int taskEntryOffset = 5;
also updated this

2021-07-20 16:11 UTC, BradSwain commented on src/IR/IRImpls.h
> +    return llvm::cast<llvm::Function>(taskFunc);
also updated this

2021-07-20 16:30 UTC, BradSwain commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
I don't know of a clean way to do this actually.

We cannot put a virtual function on Event and then define it for implementations of the Event interfaces like:

```cpp
class Event {
  public:
      [[nodiscard]] virtual const std::shared_ptr<const race::IR> getSharedIRInst() const = 0;
      [[nodiscard]] virtual const race::IR *getIRInst() const = 0;
};

class ForkEventImpl : public ForkEvent {
  const std::shared_ptr<const ForkIR> fork;
  public:
    [[nodiscard]] inline const std::shared_ptr<const ForkIR> getSharedIRInst() const override { return fork; }
    [[nodiscard]] inline const race::ForkIR *getIRInst() const override { return fork.get(); }
};
```

The `getIRInst` functio works because `const race::ForkIR *` is derived from `const race::IR *`.

But a `getSharedIRInst` wont work in the same way because the pointer is wrapped in a class.
`std::shared_ptr<const race::ForkIR>` and `std::shared_ptr<const race::IR>` have no relation.

The only way I can think to do this off the top of my head is to "cast" the shared_ptr up, then back down wherever it is used:

```cpp
class Event {
  public:
      [[nodiscard]] virtual const std::shared_ptr<const race::IR> getSharedIRInst() const = 0;
};

class ForkEventImpl : public ForkEvent {
  const std::shared_ptr<const ForkIR> fork;
  public:
    [[nodiscard]] inline const std::shared_ptr<const IR> getSharedIRInst() const override { 
      // "cast" up
      std::shared_ptr<IR> shared(fork, fork.get());
      return shared; 
    }
};

void example() {
   std::shared_ptr<IR> ir = forkEvent->getSharedIRInst();
   // "cast" down
  if (ir.get()->type == IR::Type::OpenMPTaskFork) {
    std::shared_ptr<const OpenMPTaskFork>(ir, llvm::cast<OpenMPTaskFork>(ir.get()));
  }
}
```

but this is a little ugly.

2021-07-20 16:43 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +}
updated

2021-07-20 16:44 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +bool handleOMPEvents(const CallIR *callIR, TraceBuildState &state, bool isMasterThread) {
updated

2021-07-20 17:29 UTC, BradSwain commented on src/IR/Builder.h
> +};
updated

2021-07-20 18:10 UTC, bz-liu commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
I feel why Brad put it here is because we can directly use this information during trace construction.
`Master` is just a `omp fork` we selected from the created twin omp thread (in `generatedFunctionSummary`) to be the master thread.

2021-07-20 18:16 UTC, addison-coderrect commented on src/Analysis/HappensBeforeGraph.cpp
> +  if (fork) return fork.value();
No further instances of this fork are used, only shadowed variables of the same name. Don't need an assignment, even, afaik

2021-07-20 18:32 UTC, bz-liu commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
However, I just checked
https://github.com/coderrect-inc/OpenRace/blob/ec1502eb470aeb27be4a27f7bf0503977ec9af7f/src/IR/Builder.cpp#L217-L218

I feel this is right and we should keep it.

2021-07-20 18:33 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +  if (fork) return fork.value();
>afaik

What does this mean?

2021-07-20 18:47 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +  if (fork) return fork.value();
updated.

2021-07-20 18:47 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +// recursively find the root spawnsite (from #pragma omp parallel) for this event
updated.

2021-07-20 18:47 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +// (event1 always has the thread trace with full irs)
updated.

2021-07-20 18:48 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  // get omp block contains the event
updated.

2021-07-20 18:49 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (!region1 || !region2) {  // should have block
updated.

2021-07-20 18:49 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  // auto const loopRegions = ;
updated.

2021-07-20 18:49 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +// only use this when no tasks in single block
updated.

2021-07-20 18:49 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (event->getIRInst()->type == race::IR::Type::OpenMPReduce) {
updated.

2021-07-20 18:49 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.h
> +  // Return true of the other region is the same region in the IR
updated.

2021-07-20 18:49 UTC, bz-liu commented on src/IR/Builder.cpp
> +          auto ompFork = std::make_shared<OpenMPFork>(callInst, true);
updated.

2021-07-20 18:50 UTC, bz-liu commented on src/LanguageModel/OpenMP.h
> +}
updated.

2021-07-20 18:50 UTC, bz-liu commented on src/Trace/ProgramTrace.h
> +
updated.

2021-07-20 18:51 UTC, bz-liu commented on src/Trace/ProgramTrace.h
> +  // record the start of a master
updated.

2021-07-20 18:51 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +// all tasks in state.taskWOJoins should be joined when any of the following occur:
updated.

2021-07-20 18:52 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +  bool isFork = callstack.isEmpty();
updated.

2021-07-20 18:52 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +      // Only put omp task forks on master thread if spawned in single region
updated.

2021-07-20 18:52 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +      auto forkEvent = static_cast<const ForkEvent *>(event);
updated.

2021-07-20 18:52 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +      // check if need to insert joins for tasks
updated.

2021-07-20 21:52 UTC, funemy commented on src/Analysis/HappensBeforeGraph.cpp
> +  if (fork) return fork.value();
> > afaik
> 
> What does this mean?

lol, short for "As far as I know"

2021-07-20 22:03 UTC, funemy commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
Yeah, this is indeed ugly.

How about just add a method in `ForkEvent` not `Event`? Since right now `ForkEvent` is the only place we need to use such an API.

2021-07-20 22:10 UTC, funemy commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
I still think we should remove it.
kmpc_task_alloc is only related to pointer analysis. For race detection, it has no effect.
So we should just add it to `OpenMPModel::isNoEffect`?

https://github.com/coderrect-inc/OpenRace/blob/ec1502eb470aeb27be4a27f7bf0503977ec9af7f/src/IR/Builder.cpp#L220

Maybe @BradSwain for a final decision?

2021-07-20 22:15 UTC, BradSwain commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
sorry I missed this one. I will see if I can update.

and yeah, put it here because it is kind of difficult to compute during trace.

2021-07-20 22:16 UTC, BradSwain commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
Yeah makes sens to me to add to `isNoEffect`

2021-07-20 22:17 UTC, BradSwain commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
I can but same issue.

The cast will then look like

```cpp
// this line changed from IR to ForkIR
std::shared_ptr<ForkIR> ir = forkEvent->getSharedIRInst();
   // "cast" down
  if (ir.get()->type == IR::Type::OpenMPTaskFork) {
    std::shared_ptr<const OpenMPTaskFork>(ir, llvm::cast<OpenMPTaskFork>(ir.get()));
  }
```

2021-07-20 22:18 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +bool handleOpenMPMaster(const CallIR *callIR, TraceBuildState &state, bool isMasterThread) {
I will make this change

2021-07-20 22:35 UTC, BradSwain commented on src/LanguageModel/RaceModel.cpp
> +    race::OpenMPTask task(llvm::cast<CallBase>(callsite));
updated

2021-07-20 22:38 UTC, BradSwain commented on src/IR/IRImpls.h
> +using OpenMPTaskAlloc = CallIRImpl<IR::Type::OpenMPTaskAlloc>;
class has been removed.

2021-07-20 22:38 UTC, BradSwain commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
updated

2021-07-21 05:56 UTC, funemy commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
Oh yeah, I see, because in Events we are only visible up to `ForkIR`. That's unfortunate.

I'm not sure which way is better than lol. Slightly leaning towards removing it from the struct.

2021-07-21 06:00 UTC, funemy commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
Yeah, I can see that it's not very easy to compute this information during the trace.
Then we should at least add a boolean field to the struct `state` (even if we still leave the `isMasterThread` field here in IR).

2021-07-21 14:06 UTC, bz-liu commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
`isMasterThread` has been updated to a `enum` (we may have other types in the future):
https://github.com/coderrect-inc/OpenRace/blob/af1c74452e5d1ef9f3f8316e839211f2374b0c2f/src/IR/IRImpls.h#L134-L139

But why add it to `state` is necessary? The usage is like:
https://github.com/coderrect-inc/OpenRace/blob/af1c74452e5d1ef9f3f8316e839211f2374b0c2f/src/Trace/ThreadTrace.cpp#L231-L236
It is thread trace-specific, not state-specific. If we keep a boolean in `state`, we'll have an extra job to maintain the boolean correctly.

2021-07-21 17:34 UTC, funemy commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
IMO the `state` should represent the state of our interpreter (i.e., the trace builder).
And it's very natural to have a field recording the status of the current thread we are traversing.

I think conceptually having `isMasterThread` in IR is a mistake.
But if this will bring difficulty in implementation maybe we can leave it now

2021-07-21 17:36 UTC, BradSwain commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
I prefer leaving it as a struct. Both the solutions so far feel a little "hacky" and I prefer to contain the hackiness to one spot (the struct), vs. updating the API and adding those weird casts as well.

2021-07-21 17:39 UTC, bz-liu commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
I'm neutral now, how about @BradSwain ?

2021-07-21 17:41 UTC, funemy commented on src/Trace/ProgramTrace.h
> +    std::shared_ptr<const OpenMPTask> forkIR;
Yeah sure.
I took another look at the code; seems the current way is slightly simpler.
Let's keep it for now.
Marking this conversation as resolved.

2021-07-21 17:45 UTC, funemy commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
I don't have a strong opinion on this.

I'm mostly thinking of "don't expose information too early", as `isMasterThread` is a piece of information we only need in trace builder (and it can be computed there).
Maybe we can leave it

2021-07-21 18:04 UTC, BradSwain commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
I think the main benefit of including a field like `state.openmp.onMasterThread` is that we keep all "state" related info in one place.

The downside to including an extra field on the state struct is that it has to always be maintained.
Currently we only check if we are on the master thread as needed. (traversing master regions and spawning tasks in single regions ). If we include it as a field on the state struct we need to make sure the field is always correct and up to date, even if we are don't actually care whether we are on the master thread or not.

The two ways I can think of to keep the field up to date are to update the state before and after traversing a sub-thread:

```cpp
bool isForkingOpenMPMaster(const ForkIR *fork) {
  auto ompFork = llvm::dyn_cast<OpenMPFork>(fork);
  if (!ompFork) return false;
  return ompFork->isMaster();
}

// inside trace traversal
else if (auto forkIR = llvm::dyn_cast<ForkIR>(ir.get())) {
  // set state for sub-thread
  state.openmp.onMasterThread = isForkingOpenMPMaster(forkIR);
  
  // traverse sub thread here

  // Reset state for current thread
  state.openmp.onMasterThread = thread.spawnSite && isForkingOpenMPMaster(thread.spawnSite.value());

```

or just set it every time we traverse a function

```cpp
void traverseCallNode(...) {
  state.openmp.onMasterThread = thread.spawnSite && isForkingOpenMPMaster(thread.spawnSite.value());
```


As a compromise, can we add the function for computing to see if we are on the master thread to the openmp state struct?

like:

```cpp
struct OpenMPState

bool onMasterThread() {
    auto ompFork = isOpenMPThread(currentThread);
    return ompFork && ompFork->isForkingMaster();;
}
```

This means we need to also add a reference to the current thread to state though, which in itself is kind of complex because we need to make sure that reference is always kept up to date.

2021-07-21 18:47 UTC, funemy commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
As per discussion with @BradSwain, I think we can leave this as is for now.
Adding the extra field to `state` clearly brings some extra work in maintaining the `state` to be precise. 
And for now, the benefit is marginal other than the cleanliness.

Therefore, we decide not to make this change. In the future, we may need to refactor the trace builder when supporting more concurrent programming models. We can revisit this idea then.

2021-07-21 18:47 UTC, funemy commented on src/IR/IRImpls.h
> +  const bool isMasterThread;
Marking as resolved

2021-07-21 19:13 UTC, funemy requested changes
Seems most issues are addressed.
Just two more very minor changes to make.

2021-07-21 19:13 UTC, funemy commented on src/Trace/ThreadTrace.cpp
> +// TODO: the behavior might be different when this traversal is for a fork or a function call
what is this comment?
Should it be removed?

2021-07-21 19:13 UTC, funemy commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (event->getIRType() == race::IR::Type::OpenMPReduce) {
I think the namespace `race::` is not needed, can we delete it?

2021-07-21 19:16 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +// TODO: the behavior might be different when this traversal is for a fork or a function call
updated

2021-07-21 19:16 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (event->getIRType() == race::IR::Type::OpenMPReduce) {
updated

2021-07-21 19:16 UTC, funemy approved these changes
🎉 🎉 🎉

2021-07-21 19:17 UTC, BradSwain approved these changes

2021-07-21 19:21 UTC, merged

2021-07-21 19:21 UTC, BradSwain commented
:tada: :tada: :tada: