Update thread model for omp master and single
coderrect-inc/OpenRace pull request #235
Opened 2021-06-25 20:12 UTC by bz-liu

When using omp master/single(+task), there should be only one omp fork thread (we always have two) that execute this part of the code solution:
1. we will attach this part of ir to the omp fork seen first, so it only appear once
2. make sync edges between single(+task) and the first event afterwards from other parallel stmts, so guarantee the happens-before relation 

When using single(+stmt), we attach this part of ir to both omp forks, so we can find the race between two single blocks.

2021-06-25 21:53 UTC, BradSwain requested changes

2021-06-25 21:53 UTC, BradSwain commented on src/LanguageModel/OpenMP.h
> +
where is this used?

2021-06-25 21:53 UTC, BradSwain commented on src/LanguageModel/OpenMP.h
> +#include <llvm/IR/Instructions.h>
Is this include needed?

2021-06-25 21:53 UTC, BradSwain commented on src/IR/Builder.cpp
> -          // duplicate omp preprocessing should duplicate all omp fork calls
Is this comment still true?

2021-06-25 21:53 UTC, BradSwain commented on src/IR/Builder.cpp
> +              }
Instead of inserting join at SingleEnd if there is barrier in next block, can we instead just insert task joins whenever we encounter barriers?

2021-06-25 21:53 UTC, BradSwain commented on src/IR/Builder.cpp
> +            exlStartEnd.insert(std::make_pair(exlSingleStart, callInst));
Putting single on one thread only will cause us to miss races between single regions.

```cpp
#pragma omp single nowait
{ shared = 1; }

#pragma omp single nowait
{ shared = 2; }
```
there should be a race here.

2021-06-25 21:53 UTC, BradSwain commented on src/IR/Builder.cpp
> +        continue;  // skip traversing to avoid FP
Why do we skip traversing some instructions?
And which instructions are being skipped? This part is a little unclear to me.

2021-06-25 21:53 UTC, BradSwain commented on src/IR/Builder.cpp
> +          std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator itExl = exlStartEnd.find(callInst);
long type names like `std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator` can be replaced with `auto`.

2021-06-25 21:53 UTC, BradSwain commented on src/IR/Builder.cpp
> +        continue;  // skip traversing to avoid FP
Oh I think I see, we skip traversing until the end of the master/single region?

2021-06-25 21:57 UTC, bz-liu commented on src/LanguageModel/OpenMP.h
> +
not used, intermediate product, will removed.

2021-06-25 21:57 UTC, bz-liu commented on src/LanguageModel/OpenMP.h
> +#include <llvm/IR/Instructions.h>
not used, intermediate product, will removed.

2021-06-25 21:57 UTC, bz-liu commented on src/IR/Builder.cpp
> -          // duplicate omp preprocessing should duplicate all omp fork calls
lol, no, will remove

2021-06-25 21:59 UTC, bz-liu commented on src/IR/Builder.cpp
> +        continue;  // skip traversing to avoid FP
"Oh I think I see, we skip traversing until the end of the master/single region?" -> yes.

2021-06-25 22:07 UTC, bz-liu commented on src/IR/Builder.cpp
> +              }
A `__kmpc_single` and the corresponding `__kmpc_omp_task` are in the same basicblock (as shown in code comment). `tasks` here is declared inside the traversal of a basicblock, so, every `__kmpc_single` will has its matched `tasks`. If inserting join at barriers, I need to move `tasks` to the traversal of functions, and match which tasks is for which barrier (not only single has barrier). 

For `nowait` as mentioned in the code comment, if I did not see a barrier after the current basicblock that has `__kmpc_single` and `__kmpc_omp_task` (using func `hasBarrierInNextBasicBlock`), I'll skip the join.

2021-06-25 22:08 UTC, bz-liu commented on src/IR/Builder.cpp
> +            exlStartEnd.insert(std::make_pair(exlSingleStart, callInst));
I remember I pushed the code for this case. I'll push it.

2021-06-25 22:47 UTC, funemy commented on src/IR/Builder.cpp
> +            exlStartEnd.insert(std::make_pair(exlSingleStart, callInst));
I'm curious what would be the solution for this case in the single-thread model?

2021-06-25 23:29 UTC, BradSwain commented on src/IR/Builder.cpp
> -          // duplicate omp preprocessing should duplicate all omp fork calls
Why is it no longer true?

2021-06-26 01:30 UTC, bz-liu commented on src/IR/Builder.cpp
> -          // duplicate omp preprocessing should duplicate all omp fork calls
because what we did for omp master and single, which only appear in one omp fork now.

2021-06-26 01:31 UTC, bz-liu commented on src/IR/Builder.cpp
> -          // duplicate omp preprocessing should duplicate all omp fork calls
Or I misunderstand the sentence...

2021-06-26 01:31 UTC, bz-liu commented on src/IR/Builder.cpp
> +            exlStartEnd.insert(std::make_pair(exlSingleStart, callInst));
write a test case, have a try, lol

2021-06-26 01:32 UTC, bz-liu commented on src/IR/Builder.cpp
> +          std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator itExl = exlStartEnd.find(callInst);
so, long type names are not preferred?

2021-06-29 16:33 UTC, BradSwain commented on src/IR/Builder.cpp
> +            exlStartEnd.insert(std::make_pair(exlSingleStart, callInst));
Just to note for the future, I think we will let this kind of thing fail for now.
We have an idea for how to handle it later, but for now we don't want to block handling task to be able to detect races between single regions.

2021-07-06 21:42 UTC, BradSwain commented on src/IR/Builder.h
> +  std::vector<std::shared_ptr<const IR>> getInstructions() { return instructions; }
Can the tests get the instructions directly?

for example: 

```cpp
summary.instructions
```

2021-07-06 21:42 UTC, BradSwain commented on src/IR/Builder.h
> +  std::set<std::shared_ptr<OpenMPTask>> tasks;  // indicate whether there are omp tasks, for omp use only
Why is a set of tasks needed?

2021-07-06 21:42 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +  auto tasks = summary.tasks;
I think these lines will make copies of the vector/set.

You can do `auto const & irFunc = summary.instructions` to get a constant reference to the underlying data without copying.

2021-07-06 21:42 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +            if (start1 < eid1 && end1 > eid1 && start2 < eid2 && end2 > eid2) {  // check omp block contains the event
`Region::contains` can be used to check if an event ID is within a region.

2021-07-06 22:02 UTC, BradSwain commented
Something happened. I only saw some of the changes. I will review the full change now.

2021-07-07 02:50 UTC, BradSwain requested changes

2021-07-07 02:50 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +        std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator itExl = state.exlStartEnd.find(inst);
Prefer `auto` over long type names like `std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator`.

See iso cpp guidelines [ES.11](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es11-use-auto-to-avoid-redundant-repetition-of-type-names)

2021-07-07 02:50 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +      // handle omp single
To keep the `traverseCallNode` function a little cleaner, I think any long-ish OpenMP specific stuff should be wrapped into another function.

2021-07-07 02:50 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +          // do nothing: we want the stmt to be shown in both omp forks
For now I think it is more clear to always put single on the "main" OpenMP thread only.
It is easier to reason about than putting it on main thread under some conditions, and not under others.

2021-07-07 02:50 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +          }
I think this logic is a little wrong.

I don't think tasks should care about the end of a single region.

I think tasks should be added to the `taskWOJoins` list as soon as they are created, and then all tasks in that list should be joined when any of the following occur:
1) a barrier is encountered (from anywhere, not just after single)
2) taskwait is encountered
3) the end of the parallel region is encountered.

Case 2 may be something we add support for later, but I think we should at least handle case 1 and 3 for now.

2021-07-07 02:50 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +
should be removed

2021-07-07 02:50 UTC, BradSwain commented on tests/integration/openmp.test.cpp
> +  checkOracles(oracles, "integration/openmp/");
nice that we can pass all the test cases!

2021-07-07 02:50 UTC, BradSwain commented on src/Analysis/HappensBeforeGraph.cpp
> +  // omp task without single will have no barrier/join to omp parallel -> add fake join
This comment doesn't look to correspond to any code?

2021-07-07 02:50 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +    llvm::outs() << "\n";
remove printing

2021-07-07 02:50 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +    // so, if either event is encountered before finding a reduce that contains both event1
"that contains both event1" should be changed to "that contains event1"

2021-07-07 02:50 UTC, BradSwain commented on src/IR/Builder.cpp
> -          // duplicate omp preprocessing should duplicate all omp fork calls
Should the comment be added back?

2021-07-07 02:50 UTC, BradSwain commented on src/RaceDetect.cpp
> -          ompAnalysis.bothInMasterBlock(write, other) || race::OpenMPAnalysis::insideCompatibleSections(write, other)) {
Can `inSameSingleBlock` be removed as well?

2021-07-07 02:50 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +        std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator itExl = state.exlStartEnd.find(inst);
prefer auto over `std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator`.

2021-07-07 14:20 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +}
So, I have some comments in the code (copied below):
```cpp
const ForkEvent *getCorrespondingFork(const JoinEvent *join, const ProgramTrace &program) {
  if (join->getIRInst()->type == IR::Type::OpenMPTaskJoin) {
    // all joins of openmp tasks have the same getThreadHandle() value: %.kmpc_loc.addr.i,
    // so we use getThreadEntry() to distinguish them
```
An example IR is like: 
```cpp
  %12 = call i32 @__kmpc_omp_task(%struct.ident_t* nonnull %.kmpc_loc.addr.i, i32 %3, i8* %8) #5, !dbg !136, !noalias !133
...
  %19 = call i32 @__kmpc_omp_task(%struct.ident_t* nonnull %.kmpc_loc.addr.i, i32 %3, i8* %15) #5, !dbg !141, !noalias !133
```
where `%.kmpc_loc.addr.i` is the thread ID/handler. Instead, we need to match `%12` and `%19` with the task joins.

2021-07-07 14:23 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +      llvm::errs() << "Cannot use getForkWithEntry to find the fork of omp tasks. \n";
The same reason above.

2021-07-07 14:25 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +              thread1.getEvent(end1)->getInst() == thread2.getEvent(end2)->getInst()) {  // same start/end ir
Sure.

2021-07-07 14:28 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  // Omp threads in same team may or may not have identical traces so we see them separately
yes, maybe `getRegions` can be specific to the `event` that we want to check, like:
```cpp
auto const regions1 = getRegions<Start, End>(thread1, event1);
```
then `regions1` is only the region that contains `event1`.

2021-07-07 14:30 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
>  }
there are two types of `single`: `single + task` and `single + stmt`.
`single + task`: we only put the single events on one thread, as you said.
`single + stmt`: we still put the statements in the block on both threads to check the races between the stmts.

2021-07-07 14:31 UTC, bz-liu commented on src/RaceDetect.cpp
> +                   << "\n";
some test cases will crash on the line with `getDebugLoc`, idk why. if so, I comment those lines off.

2021-07-07 14:43 UTC, bz-liu commented on src/Trace/ProgramTrace.h
> +  const llvm::CallBase *exlSingleEnd = nullptr;
`single` is a bit different from `master`: it is arranged to a random thread, not specifically the master thread. 
Actually, your concern here only happen when it is `single + tasks`. 
If the single block has only stmts, we will not record this single in `exlSingleStart` (we only record `exlSingleStart` when there is `tasks` in this single block); so, the traversal will end with two single blocks with their stmts.
If If the single block has only tasks, I'll add a flag to address this case (maybe also add a test case here).

2021-07-07 14:44 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +        std::map<const llvm::CallBase *, const llvm::CallBase *>::iterator itExl = state.exlStartEnd.find(inst);
lol, lesson learned.

2021-07-07 14:45 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +      // handle omp single
Agree. will do.

2021-07-07 14:46 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +          }
Agreed, will update.

2021-07-07 14:47 UTC, bz-liu commented on tests/integration/openmp.test.cpp
> +  checkOracles(oracles, "integration/openmp/");
lol

2021-07-07 14:47 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +  // omp task without single will have no barrier/join to omp parallel -> add fake join
will do.

2021-07-07 14:48 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +    llvm::outs() << "\n";
lol, yes. will do.

2021-07-07 14:50 UTC, bz-liu commented on src/RaceDetect.cpp
> -          ompAnalysis.bothInMasterBlock(write, other) || race::OpenMPAnalysis::insideCompatibleSections(write, other)) {
why? we have two cases for single: `single + stmt` and `single + tasks`

2021-07-07 16:54 UTC, BradSwain commented on src/Analysis/HappensBeforeGraph.cpp
> +}
Sorry, I mean we can change `OpenMPTask::getThreadHandle` to look like:

```cpp
[[nodiscard]] const llvm::Value *OpenMPTask::getThreadHandle() const override {
  return getThreadEntry();
}
```

The `ForkIR::getThreadHandle` api just needs to return some value that will uniquely identify the thread.
It does not have to be the `%kmpc_loc.addr.i`. If we can identify tasks by their entry functions, we can use that as the identifier instead.

2021-07-07 18:23 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +}
Agreed. will do.

2021-07-08 14:39 UTC, bz-liu commented on src/Trace/ProgramTrace.h
> +  const llvm::CallBase *exlSingleEnd = nullptr;
I update this a bit:
```cpp
using OMPStartEnd = std::map<const llvm::CallBase *, const llvm::CallBase *>;

struct TraceBuildState {

  ThreadID currentTID = 0;

  std::map<ThreadID, OMPStartEnd> tid2ExlStartEnd;  // record a map of tid to a set of traversed single(+task)/master blocks
  ...
```
This avoids the problem that "the same CallBase can be used for multiple master/single regions in a trace".

Your suggestion of using flag `isOpenMPMasterThread` is much simpler, but may not work for the following case (I added this to a test case `tests/data/integration/openmp/task-single-call.c`):

```cpp
int x = 1;

void single() {
#pragma omp single
  {
#pragma omp task
    x++;
  }
}

int main() {
#pragma omp parallel
  {
    single();
    single();
  }

  printf("%d\n", x);
}
```
Then the traces should be like: 
```cpp
omp fork 1:
single_start
task 1 // spawn task fork 1
single_end
single_start
task 2 // spawn task fork 2
single_end

omp fork 2:
single_start
task 3 // spawn task fork 3
single_end
single_start
task 4 // spawn task fork 4
single_end
``
All the code inside each task is the same, and there should be race on `x++`. So, we need to put the tasks on both omp fork threads to find the race. 

This is because the function call `single()` breaks our previous model of omp. I added a flag `isFork` to make sure we can have traces like above for the above special test case: if `isFork = true`, we still use our previous model (single+task only placed in the first omp fork thread); if `isFork = false`, the task is spawned in a method call outside of `omp parallel`, we will not check and skip tasks.

2021-07-09 16:33 UTC, BradSwain requested changes

2021-07-09 16:33 UTC, BradSwain commented on src/IR/IRImpls.h
> +      llvm::errs() << "Failed to find task function. inst=" << taskAlloc << "\n";
Can this be changed to reuse the logic from `OpenMPTask`?

e.g.

```cpp
[[nodiscard]] const llvm::Value *getThreadHandle() const override { return task->getThreadHandle(); }
```

2021-07-09 16:33 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +                                 // task-single-call.ll
Why does events being empty mean this is a fork?

2021-07-09 16:33 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +      }
I think this check is redundant and can be removed.

It should be caught by the case below 
```cpp
  else if (callIR->type == IR::Type::OpenMPBarrier) {
    insertTaskJoins(events, state.taskWOJoins, einfo);
  }
```

2021-07-09 16:33 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +    state.exlMasterStart = inst;
I don't understand what this is doing

2021-07-09 16:52 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.h
>    inline bool contains(EventID e) const { return end >= e && e >= start; }
I need a field `const ThreadTrace& thread;`, this is the only diff. is there a way to integrate `Region` and `Block`?

2021-07-09 16:54 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  if (!eSpawn) return nullptr;
`std::nullopt`

2021-07-09 16:54 UTC, bz-liu commented on src/RaceDetect.cpp
> +    }
will remove

2021-07-09 16:56 UTC, bz-liu commented on tests/data/integration/openmp/task-single-call.c
> +#include <omp.h>
will remove

2021-07-09 16:58 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +    usedTaskForks;  // avoid inserted fake task join to find the same task fork, e.g., task-yes.c
put `usedTaskForks` as a field of `HappensBeforeGraph`?

2021-07-09 17:01 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +      usedTaskForks.insert(fork);
To avoid inserted fake task join to find the same task fork, e.g., task-yes.c.
But this is still not a good solution, since tasks can have the same ir in their task joins, e.g., task-single-call.c, cannot distinguish them. 
Need a better solution, like store the task event id to its corresponding task join as a field.

2021-07-09 17:04 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +// TODO: both tasks have the same ir in task joins, e.g., task-single-call.c, cannot distinguish
An example IR is (from task-single-call.c):
```cpp
---Thread1  (Spawned by T0:1)
...
8 Fork	  %10 = call i32 @__kmpc_omp_task(%struct.ident_t* nonnull %.kmpc_loc.addr, i32 %2, i8* %8) #5, !dbg !21
9 Join	  %10 = call i32 @__kmpc_omp_task(%struct.ident_t* nonnull %.kmpc_loc.addr, i32 %2, i8* %8) #5, !dbg !21
...
22 Fork	  %10 = call i32 @__kmpc_omp_task(%struct.ident_t* nonnull %.kmpc_loc.addr, i32 %2, i8* %8) #5, !dbg !21
23 Join	  %10 = call i32 @__kmpc_omp_task(%struct.ident_t* nonnull %.kmpc_loc.addr, i32 %2, i8* %8) #5, !dbg !21
...
```
The tasks are spawned from a function call, so cannot distinguish them by their return value as before (i.e., `%10`).

2021-07-09 17:04 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +
idk, maybe IDE adds this line.

2021-07-09 17:05 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +
no, but you suggested lambda before, lol

2021-07-09 17:06 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +      return new Block(it->start, it->end, thread);
I tried, but I also needs to return empty/nothing/nullptr in this function to represent I cannot find such a block. And I tried the empty default constructor of Block, which has compile error.

2021-07-09 17:09 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.h
> +  Block(EventID start, EventID end, const ThreadTrace& thread) : start(start), end(end), thread(thread){};
I need a field `const ThreadTrace& thread;` when we are checking the start/end of an event in a task spawn.

2021-07-09 17:12 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +                                 // task-single-call.ll
maybe I need to find another way?

2021-07-09 17:14 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +    state.exlMasterStart = inst;
actually same as before, to check whether there is a traversed master/single start that is the same as `inst`; if so, skip it until we see the master/single end.

2021-07-09 18:21 UTC, BradSwain commented on src/Analysis/HappensBeforeGraph.cpp
> +      usedTaskForks.insert(fork);
> Need a better solution, like store the task event id to its corresponding task join as a field.

I think this should be doable since we insert the task join from the task spawn event.
Not sure the best way to update the Event code to handle this case though.

2021-07-09 18:23 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +
oh I see.
In this case it can just be a normal function.
I thought the function needed to capture some local variable before.

2021-07-09 20:42 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +      usedTaskForks.insert(fork);
I added a field (of type `const ForkEvent *`) for `JoinEventImpl` for `OpenMPTaskJoin`, to match the thread forks when calling `getCorrespondingFork()` and to get the correct HB edge.

2021-07-09 22:07 UTC, bz-liu commented on src/IR/Builder.h
> +  std::vector<std::shared_ptr<const IR>> getInstructions() { return instructions; }
updated

2021-07-09 22:09 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +  auto tasks = summary.tasks;
updated.

2021-07-09 22:10 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +    usedTaskForks;  // avoid inserted fake task join to find the same task fork, e.g., task-yes.c
`usedTaskForks` has been removed.

2021-07-09 22:11 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +
updated.

2021-07-09 22:12 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +                                 // task-single-call.ll
now using `bool isFork = callstack.isEmpty()`, an empty call stack means the start of the thread traversal

2021-07-13 20:05 UTC, BradSwain commented on src/Trace/ThreadTrace.cpp
> +    state.exlMasterStart = inst;
Note to self: what happens if there is overlap

2021-07-15 19:03 UTC, merged