Threadprivate fix
coderrect-inc/OpenRace pull request #255
Opened 2021-07-12 20:05 UTC by BradSwain

Closes #254 

Add some logic to the threadprivate check to see if the pointer being operated on flows from a global threadlocal object.

2021-07-12 20:24 UTC, funemy approved these changes
Looks good to me for this _specific_ case. So I approved.

Would it make more sense to iterate over use-def chain?

2021-07-12 20:35 UTC, BradSwain commented
I think no, because we only want to mark stuff as thread local if the pointer being operated on must point to a global.

If there is something like:

```cpp
int threadlocal; // this is thread local

// ...
#pragma omp parallel
{
  int x = threadlocal + 1;
}
```

Following the entire use-def chain will result in `x` being marked as threadlocal because `x` "uses" `threadlocal`.

I think we just want  to follow llvm instructions that copy the pointer. 
I think load and GEP are the only two that do this, but I'm not entirely sure.

2021-07-12 21:41 UTC, funemy requested changes
According to your issue, you should also handle `StoreInst`?

2021-07-12 21:59 UTC, BradSwain commented
Updating to move this check to happen during analysis phase and use PTA.

2021-07-14 22:18 UTC, funemy requested changes

2021-07-14 22:18 UTC, funemy commented on src/Analysis/ThreadLocalAnalysis.cpp
> +  // where O1 is the onlt thread local object
"onlt" -> "only"

2021-07-14 22:18 UTC, funemy commented on src/Analysis/ThreadLocalAnalysis.cpp
> +  std::sort(otherPtsTo.begin(), otherPtsTo.end());
Why sorting is needed first?

2021-07-14 22:18 UTC, funemy commented on src/Analysis/ThreadLocalAnalysis.cpp
> +    llvm::outs() << *val << " " << (global && global->isThreadLocal()) << "\n";
do we want to keep this debugging log?

2021-07-14 22:18 UTC, funemy commented on src/IR/Builder.cpp
>  bool hasThreadLocalOperand(const llvm::Instruction *inst) {
is this function used anywhere?

2021-07-14 22:26 UTC, BradSwain commented on src/Analysis/ThreadLocalAnalysis.cpp
> +    llvm::outs() << *val << " " << (global && global->isThreadLocal()) << "\n";
oops, lol. we do not.

2021-07-14 22:27 UTC, BradSwain commented on src/Analysis/ThreadLocalAnalysis.cpp
> +  std::sort(otherPtsTo.begin(), otherPtsTo.end());
I think set_intersection requires the list to be sorted.

2021-07-14 22:28 UTC, BradSwain commented on src/IR/Builder.cpp
>  bool hasThreadLocalOperand(const llvm::Instruction *inst) {
yeah. Used in the load/store branches of function summary builder

2021-07-14 22:29 UTC, funemy commented on src/Analysis/ThreadLocalAnalysis.cpp
> +  std::sort(otherPtsTo.begin(), otherPtsTo.end());
I see, I forgot that lol

2021-07-14 22:31 UTC, BradSwain commented on src/Analysis/ThreadLocalAnalysis.cpp
> +  std::sort(otherPtsTo.begin(), otherPtsTo.end());
I double checked
> Elements are compared using operator< and the ranges must be sorted with respect to the same.
https://en.cppreference.com/w/cpp/algorithm/set_intersection

2021-07-14 22:33 UTC, funemy approved these changes
LGTM

2021-07-14 22:44 UTC, merged