Work on solving unpassed array index DRB tests
coderrect-inc/OpenRace pull request #268
Opened 2021-07-16 22:18 UTC by bz-liu

**NOTE**: This branch should be merged after omp-task is merged to develop.

Add a simple array index analysis.

2021-07-22 16:15 UTC, BradSwain requested changes
Still reviewing the main changes but there are a few small changes to be made first.

The .ll files need to be removed and  looks like during merging some stuff was undone (see comments below).

2021-07-22 16:15 UTC, BradSwain commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
This can be deleted

2021-07-22 16:15 UTC, BradSwain commented on src/IR/IRImpls.h
> +    return llvm::cast<llvm::Function>(taskFunc);
this can be reverted back to

```
    auto taskAlloc = inst->getArgOperand(taskAllocOffset)->stripPointerCasts();
    auto taskAllocCall = llvm::dyn_cast<llvm::CallBase>(taskAlloc);
    assert(taskAllocCall && "Failed to find task alloc call");
    assert(OpenMPModel::isTaskAlloc(taskAllocCall->getCalledFunction()->getName()) && "failed to find task alloc");

    return taskAllocCall->getArgOperand(taskEntryOffset)->stripPointerCasts();
```

2021-07-22 16:15 UTC, BradSwain commented on src/IR/IRImpls.h
> +
This can be deleted

2021-07-22 16:15 UTC, BradSwain commented on src/RaceDetect.cpp
> +      other->getInst()->print(llvm::outs(), false);
Does

```
llvm::outs() << *other->getInst() << "\n\t";
```

work here?

2021-07-22 16:15 UTC, BradSwain commented on src/RaceDetect.cpp
> +  race::SimpleArrayAnalysis arrayAnalysis(ompAnalysis);
I think `SimpleArrayAnalysis` should be a member of `OpenMPAnalysis` since it is only ever used in the context of OpenMP.

The existence of an additional class can then be hidden from the end user by keeping the API the same. E.g.

```cpp
class OpenMPAnalysis {
  SimpleArrayAnalysis arrayAnalysis;

public:
   bool isLoopArrayAccess(...) { return arrayAnalsysis.isLoopArrayAccess(...); }
};
```

or if it makes more sense we could expose the array index analysis as a public field  on OpenMPAnalysis.

```cpp
  ompAnalysis.array.canIndexOverlap(...);
```

2021-07-22 16:20 UTC, bz-liu commented
I just figured out DRB073
```
// 73 broken debug info
// TEST_LL("DRB073", /*TODO*/, EXPECTED(/*TODO*/))
```
is also array-related, and mentioned in issue #230.

Will work on this and ask for review later.

2021-07-23 13:19 UTC, bz-liu commented on src/RaceDetect.cpp
> +      other->getInst()->print(llvm::outs(), false);
Works!

2021-07-23 13:20 UTC, bz-liu commented on src/RaceDetect.cpp
> +  race::SimpleArrayAnalysis arrayAnalysis(ompAnalysis);
I'll update this change.

2021-07-23 17:19 UTC, bz-liu commented
issue #238 is fixed

2021-07-23 18:27 UTC, bz-liu commented on src/RaceDetect.cpp
> +  race::SimpleArrayAnalysis arrayAnalysis(ompAnalysis);
made `SimpleArrayAnalysis` as a member of `OpenMPAnalysis`

2021-07-23 18:27 UTC, bz-liu commented on src/IR/IRImpls.h
> +
removed.

2021-07-23 18:27 UTC, bz-liu commented on src/IR/IRImpls.h
> +    return llvm::cast<llvm::Function>(taskFunc);
updated.

2021-07-23 18:27 UTC, bz-liu commented on src/IR/IR.h
> +    OpenMPTaskAlloc,
deleted.

2021-07-23 18:27 UTC, bz-liu commented on src/IR/IRImpls.h
> +  constexpr static unsigned int threadEntryOffset = 2;
updated.

2021-07-23 18:27 UTC, bz-liu commented on src/Analysis/HappensBeforeGraph.cpp
> +// TODO: both tasks have the same ir in task joins, e.g., task-single-call.c, cannot distinguish
removed.

2021-07-26 19:34 UTC, BradSwain requested changes

2021-07-26 19:34 UTC, BradSwain commented on src/Analysis/SimpleArrayAnalysis.cpp
> +bool isPerfectlyAligned(const GetElementPtrInst *idx, std::string parallelIdx, bool isInnerIdx) {
should the `idx` var be named `gep` here?

2021-07-26 19:34 UTC, BradSwain commented on src/Analysis/SimpleArrayAnalysis.cpp
> +bool isPerfectlyAligned(const GetElementPtrInst *idx, std::string parallelIdx, bool isInnerIdx) {
Also I think this function can be split into two functions?

one version with just `idx` for single-dimen arrays, and another with `idx, parallelIDx` for multi-dimen array

2021-07-26 20:14 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (event->getIRInst()->type == race::IR::Type::OpenMPReduce) {
updated.

2021-07-26 20:14 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.h
> +struct Region;
removed.

2021-07-26 20:15 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.h
> +#include <Trace/ThreadTrace.h>
removed.

2021-07-26 20:15 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +
what is license comment?

2021-07-26 20:15 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.h
> +
added.

2021-07-26 20:15 UTC, bz-liu commented on src/CMakeLists.txt
> +    RaceDetect.cpp Analysis/SimpleArrayAnalysis.cpp)
updated.

2021-07-26 20:15 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.h
> +  // return true if this event is in a omp fork loop
updated.

2021-07-26 20:17 UTC, bz-liu commented on tests/integration/dataracebench.test.cpp
> +                 "DRB052-indirectaccesssharebase-orig-no.c:120:13 DRB052-indirectaccesssharebase-orig-no.c:119:13", ))
updated to a unpassed test.

2021-07-27 21:25 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
>  }
Updated, changed the API name to `isLoopArrayAccessWOIdxOverlap` = is loop array access without array index overlaps

2021-07-27 21:26 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +    auto storeBase = event1->getInst()->getOperand(1);  // must be write
this part of the code has been removed.

2021-07-27 21:26 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  }
added.

2021-07-27 21:26 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +// PS: this is valid when the loop iterate over the index, e.g., j not i,
updated.

2021-07-27 21:27 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +bool isPerfectlyAligned(const GetElementPtrInst *idx, std::string parallelIdx, bool isInnerIdx) {
`idx` is udpated to `gep`, but I kept the function `isPerfectlyAligned`, if changing to two functions (one for multi-dim and another for one-dim), we will have some redundant code.

2021-07-27 21:28 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  if (idxes.size() > 1) {  // reversely check
I updated this part to a for loop to avoid those ugly code.

2021-07-27 21:29 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  std::string getOuterMostIdxName() { return outerMostIdxName; }
This struct has a lot changes: updated to `std::optional` and include some logics inside the constructor.

2021-07-27 21:29 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +bool isMathCast(unsigned int op) { return op >= 38 && op <= 46; }
updated to llvm APIs

2021-07-27 21:30 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +// c. it is the index variable but is not private d. it is the index variable but not in omp parallel region;
updated.

2021-07-27 21:30 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +std::string getIdxForIdxprom(Value *idx) {
updated.

2021-07-27 21:30 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +    return idx->getName().str();
updated.

2021-07-27 21:30 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  return "";
updated.

2021-07-27 21:31 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  auto sext = llvm::dyn_cast<llvm::SExtInst>(idx);
updated.

2021-07-27 21:37 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +    // if so, this is nested loop with the collapse clause: should have no dependency and no race
udpated. added some logics in `ArrayAccess`.

2021-07-27 21:38 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  return "";
updated.

2021-07-27 21:38 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +}
updated the var name, added the assertion.

2021-07-27 21:38 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +};
changed to `std::vector`

2021-07-29 13:42 UTC, BradSwain requested changes

2021-07-29 13:56 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +            // c. it is the index variable but is not private d. it is the index variable but not in omp parallel
clang format ...

2021-07-29 14:05 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  auto nonConst = ir->getOperand(0);
no, some math operations (e.g., cast) only has one operand.

2021-07-29 14:25 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +std::optional<llvm::StringRef> getIdxForIdxprom(Value *idx) {
changed to `getInductionVarNameForIdxprom`

2021-07-29 14:30 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +    if (event->getIRType() == race::IR::Type::OpenMPReduce) {
updated.

2021-07-29 15:54 UTC, bz-liu commented on src/Analysis/SimpleArrayAnalysis.cpp
> +  }
replaced by a cleaner and shorter piece of code.

2021-07-29 16:37 UTC, BradSwain approved these changes

2021-07-29 16:37 UTC, merged