ThreadLocal optimisations
coderrect-inc/OpenRace pull request #288
Opened 2021-07-28 21:23 UTC by addison-coderrect

This pre-sorts (and removes the repeated sorting) of memory access events as required by threadlocal's set intersection.

2021-07-28 21:27 UTC, addison-coderrect commented
This optimisation is still relatively minor; reduces 10% of overhead caused by isLocalThreadAccess. This is because std::sort checks if the target is already sorted, which, in this case, it would be.

2021-07-29 00:20 UTC, BradSwain requested changes

2021-07-29 00:20 UTC, BradSwain commented on src/RaceDetect.cpp
> +
I think its better to do the sorting in thread local analysis (or both here and in thread local analysis).

If in the future we change/move the sorting here thread local analysis will silently break and it may be difficult to figure out why.
If we include the sort in the thread local analysis that kind of bug is much less likely to occur in the future.

Some potential solutions:
 - Add an assert that checks the vectors are sorted in thread local analysis
 - leave this "pre-sort" here and add back the sorting in thread local analysis. Sorting an already sorted vector should be relatively fast.
 - Build and store a separate sorted vector during thread local analysis construction
 - something else entirely 

Pros/cons to each. What do you think is best?

2021-07-29 00:27 UTC, addison-coderrect commented on src/RaceDetect.cpp
> +
The real speed advantage is relatively slim, all things considered. Perhaps there is a better approach to this optimisation...

2021-07-29 01:05 UTC, addison-coderrect commented
Found a much better way to do this.

2021-07-29 01:05 UTC, closed without merging