Add top-down search to find guardedblock inter-procedurally; add cache
coderrect-inc/OpenRace pull request #300
Opened 2021-08-02 21:14 UTC by bz-liu

2021-08-03 19:46 UTC, BradSwain commented
I'm still working on a full review, but I just realized this approach may miss some cases.

```cpp
#pragma omp parallel
  {
    int tid = omp_get_thread_num();

    if (tid == 1) {
      write_val(&counter, tid);
    }
    write_val(&counter, tid);
  }
```

In this example there is no self race on the first call to `write_val`, but there should be a self race on the second call to `write_val` and a race between the first and second calls to `write_val`.

I think the current implementation will consider `write_val` to be guarded by the  `(tid == 1)` check and report no races. Is that the case?

2021-08-03 20:03 UTC, bz-liu commented
Yes, I just added and tried the above code. Then, maybe we can borrow the patten when we build trace for `single/master`: 
we put a start node (GetThread) at the call of `omp_get_thread_num ` and its corresponding end node (EndGetThread) at the exit of `if (tid == 1) { ... }`, 
like:

```cpp
---Thread1  (Spawned by T0:4)
0 GetThread	  %call.i = call i32 @omp_get_thread_num() #5, !dbg !35
1 Call	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !40
2 Write	  store i32 %val, i32* %dest, align 4, !dbg !21, !tbaa !22
3 EndCall	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !40
*  EndGetThread    %call.i = call i32 @omp_get_thread_num() #5, !dbg !35
4 Call	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !43
5 Write	  store i32 %val, i32* %dest, align 4, !dbg !21, !tbaa !22
6 EndCall	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !43
---Thread2  (Spawned by T0:5)
0 GetThread	  %call.i = call i32 @omp_get_thread_num() #5, !dbg !35
1 Call	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !40
2 Write	  store i32 %val, i32* %dest, align 4, !dbg !21, !tbaa !22
*  EndGetThread    %call.i = call i32 @omp_get_thread_num() #5, !dbg !35
3 EndCall	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !40
4 Call	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !43
5 Write	  store i32 %val, i32* %dest, align 4, !dbg !21, !tbaa !22
6 EndCall	  call void @write_val(i32* nonnull %counter, i32 %call.i) #5, !dbg !43
```

In the GetThread/EndGetThread node, we store the guarded Thread ID. Then, when we compare, we can check whether a read/write is in between a region of GetThread/EndGetThread and its guarded Thread ID.

2021-08-03 20:09 UTC, BradSwain commented
I think this method should work, but I don't think we should use `omp_get_thread_num` as the marker because it can be used in different situations as well.

Maybe we can extend the existing analysis to compute the start/end event of a guarded block, use those to construct a list of guarded regions, and then to see if an even is guarded we can just compare the event IDs.

2021-08-03 20:14 UTC, bz-liu commented
Agreed .
The following start/end points are more accurate. 
```cpp
#pragma omp parallel
  {
    int tid = omp_get_thread_num();

    if (tid == 1) { // the start of guarded block
      write_val(&counter, tid);
    } // the end of guarded block 
    write_val(&counter, tid);
  }

```

2021-08-03 20:15 UTC, BradSwain commented
Yeah looks good, but I think identifying the event that corresponds to the end of the guarded region may be tricky.

2021-08-03 20:16 UTC, bz-liu commented
> the end of the guarded region

The tricky part is to locate where is the end of the if branch. Will add some test cases about this.

2021-08-10 19:14 UTC, BradSwain requested changes
I don't think we should add a new event type to handle this feature and I don't think the logic for doing this analysis should be done during trace construction.

Maybe we can add a preprocessing pass that looks for the guarded block pattern and inserts a fake call to make the start/end of the guarded region?

Then these can be automatically turned into extern call events by the existing code and the `inRegion` logic can be used to figure out if two events are guarded by the same thread id during the analysis phase.

2021-08-10 19:14 UTC, BradSwain commented on src/IR/IR.h
> +    None,
I don't think we should have `None` type. I think we should have a unique type for each IR class.

2021-08-10 19:14 UTC, BradSwain commented on src/Trace/Event.h
> +  enum class Type { Read, Write, Fork, Join, Lock, Unlock, Barrier, Call, CallEnd, ExternCall, GuardStart, GuardEnd };
I don't think GuardStart/End should be considered a new event type.

Events should be considered the highest abstraction of operations that we care about to detect data races.
Events should not be specific to the underlying parallelism system used (e.g. openmp, pthread, std::thread, etc.)

2021-08-10 20:17 UTC, bz-liu commented
> Maybe we can add a preprocessing pass that looks for the guarded block pattern and inserts a fake call to make the start/end of the guarded region?

This is a solution.

2021-08-13 17:12 UTC, BradSwain requested changes

2021-08-13 17:12 UTC, BradSwain commented on src/LanguageModel/OpenMP.h
> +}
Because these strings are used in other files, they can be made into named constants a referred to from preprocessing as well.

```suggestion
// Custom named functions we insert during pre-processing to mark guarded regions
const std::string OpenMPThreadGuardStart{"omp_get_thread_num_guard_start"};
const std::string OpenMPThreadGuardEnd{"omp_get_thread_num_guard_end"};

inline bool isGetThreadNumGuardStart(const llvm::StringRef& funcName) {
  return funcName.equals(OpenMPThreadGuardStart);
}
inline bool isGetThreadNumGuardEnd(const llvm::StringRef& funcName) { return funcName.equals(OpenMPThreadGuardEnd); }
```

2021-08-13 17:12 UTC, BradSwain commented on src/PreProcessing/Passes/InsertFakeCallForGuardBlocks.h
> +    guardEndFn = generateFakeFn("omp_get_thread_num_guard_end", context, module);
These strings can be replaced by referencing the named constants in LanguageModel/OpenMP.h

2021-08-13 17:12 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +  };
Is there a case where this wont be true?

2021-08-13 18:07 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +    auto const &ir = summary.at(i);
no, will update.

2021-08-13 18:11 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +bool haveSameTID(const Event *event1, const Event *event2) {
then why https://github.com/coderrect-inc/OpenRace/blob/5a0cfb159a9b9dcced1c2d0bd5b0a9a4fc3892a3/src/Analysis/OpenMPAnalysis.cpp#L132-L134
needs a template?

2021-08-13 18:14 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +  };
maybe this should be an assertion, not a check.

2021-08-13 18:14 UTC, BradSwain commented on src/Analysis/OpenMPAnalysis.cpp
> +bool haveSameTID(const Event *event1, const Event *event2) {
looks like it doesn't need to be either now.

In the past we used `inSame` for single and master, but now it is only used for single.

2021-08-13 18:15 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +bool haveSameTID(const Event *event1, const Event *event2) {
I see, I'll update both.

2021-08-13 20:01 UTC, bz-liu commented on src/Trace/ThreadTrace.cpp
> +#include "Analysis/OpenMP/OpenMP.h"
no, will remove.

2021-08-13 20:30 UTC, bz-liu commented on src/Analysis/OpenMPAnalysis.cpp
> +bool haveSameTID(const Event *event1, const Event *event2) {
https://github.com/coderrect-inc/OpenRace/blob/5a0cfb159a9b9dcced1c2d0bd5b0a9a4fc3892a3/src/Analysis/OpenMPAnalysis.cpp#L154-L160

If we remove the template, the `Start` and `End` in `getContainingRegion` will be undefined. If we need to remove template, probably also remove the following template:

https://github.com/coderrect-inc/OpenRace/blob/5a0cfb159a9b9dcced1c2d0bd5b0a9a4fc3892a3/src/Analysis/OpenMPAnalysis.cpp#L186-L189

since 1st one only used by `single` and 2nd only used by the guard of `omp_get_thread_num` now.

2021-08-14 04:27 UTC, BradSwain approved these changes

2021-08-14 04:28 UTC, merged