Add code to measure coverage of openrace
coderrect-inc/OpenRace pull request #306
Opened 2021-08-10 18:53 UTC by bz-liu

The coverage includes: 
- #function analyzed in openrace/#function in the whole program IR

2021-08-11 18:53 UTC, BradSwain requested changes

2021-08-11 18:53 UTC, BradSwain commented on src/Statistics/Coverage.cpp
> +void Coverage::computeMemAccessCoverage() {}
Is this function needed?

2021-08-11 18:53 UTC, BradSwain commented on src/Statistics/Coverage.cpp
> +          auto fn = lock->getFunction();
Is this recorded the same function as the 

```cpp
      auto eventFn = event->getFunction();
      recordFn(data.analyzed, eventFn);
```

lines above?

2021-08-11 18:53 UTC, BradSwain commented on src/Statistics/Coverage.cpp
> +        }
Are these three cases enough to discover all functions?

Other than the entry function, all function explored on a thread trace must be reached through a call event.
So, to find all functions explored by a thread trace, I think we can:
  1. Record the entry function (get the parent function of the first event on the thread trace)
  2. Record called function for each call event.

I think this should discover every explored function.

2021-08-11 18:53 UTC, BradSwain commented on src/Statistics/Coverage.cpp
> +  return os;
```suggestion
llvm::raw_ostream &race::operator<<(llvm::raw_ostream &os, const Coverage &cvg) {
  auto data = cvg.data;

  auto const nonExternTotal = data.total.size() - data.unAnalyzedExternal;

  auto asPctStr = [](size_t x, size_t total) -> std::string {
    auto const pct = static_cast<float>(x) / static_cast<float>(total);
    return llvm::formatv("{0:P}", pct);
  };

  os << "==== Coverage ====\n-> OpenRace Analyzed " << data.analyzed.size() << " out of " << data.total.size()
     << " functions (" << asPctStr(data.analyzed.size(), data.total.size()) << ").";
  os << "\n-> OpenRace Analyzed (exclude external functions) " << data.analyzed.size() << " out of " << nonExternTotal
     << " functions (" << asPctStr(data.analyzed.size(), nonExternTotal) << ")."
     << "\n#func (openrace visited): " << data.analyzed.size()
     << "\n#func (openrace unvisited): " << data.unAnalyzed.size()
     << "\n#func (external from .ll/.bc file): " << data.external
     << "\n#func (total from .ll/.bc file): " << data.total.size();

  if (data.unAnalyzed.empty()) return os;

  os << "\n\n-> " << data.unAnalyzedExternal << " out of " << data.unAnalyzed.size()
     << " unvisited functions are external functions (" << asPctStr(data.unAnalyzedExternal, data.unAnalyzed.size())
     << "%).";
  os << "\nUnvisited Functions include:\n";
  for (auto unVisit : data.unAnalyzed) {
    os << "\t" << unVisit.first << " : " << (unVisit.second ? "external" : "app") << "\n";
  }

  return os;
}
```

2021-08-11 18:53 UTC, BradSwain commented on src/Statistics/Coverage.cpp
> +  return os;
llvm has a function `formatv` that can be used to make the percentages print to two decimal places.

There was also some weirdness with the excluding external percentage. It was reporting numbers over 100%

2021-08-11 18:53 UTC, BradSwain commented on src/RaceDetect.cpp
> +    coverage.computeMemAccessCoverage();
Does it make sense to do everything during the constructor and then print?

e.g.

```cpp
Coverage coverage(program);
llvm::outs() << coverage << "\n";
```

2021-08-11 19:52 UTC, bz-liu commented on src/Statistics/Coverage.cpp
> +  return os;
> There was also some weirdness with the excluding external percentage. It was reporting numbers over 100%

which test is such case?

2021-08-11 19:59 UTC, bz-liu commented on src/Statistics/Coverage.cpp
> +          auto fn = lock->getFunction();
I updated this a bit in the latest commit. This was originally want to capture `pthread_mutex_lock ` in 
```
%call = call i32 @pthread_mutex_lock(%union.pthread_mutex_t* nonnull %mutex) ; 2
```

2021-08-11 20:21 UTC, bz-liu commented on src/Statistics/Coverage.cpp
> +        }
This should be enough. Since among all types of events, only the following 
```
Fork, Join, Lock, Unlock, Barrier, Call, ExternCall
```
must/can be function calls. However, all the call events cannot cover all called functions, e.g., `Barrier` event can be a call but it is not a `Call` event. 

I added the case for `Barrier` in the latest commit.

2021-08-12 15:48 UTC, bz-liu commented on src/Statistics/Coverage.cpp
> +        }
updated.

2021-08-12 16:18 UTC, BradSwain approved these changes

2021-08-12 16:18 UTC, BradSwain commented on src/Statistics/Coverage.cpp
> +          }
This check can be done as:

```suggestion
          if (event->getIRType() == IR::Type::OpenMPFork) {
            data.numOpenMPRegions++;
          }
```

2021-08-12 16:18 UTC, merged

2021-08-12 16:24 UTC, bz-liu commented on src/Statistics/Coverage.cpp
> +          }
Yes, I'll update this in other branches? or restore the branch?