Fix missing called function when call instruction uses alias/bitcast
coderrect-inc/OpenRace pull request #311
Opened 2021-08-11 18:25 UTC by bz-liu

Fix the missing called functions triggered by https://github.com/coderrect-inc/OpenRace/blob/1edb5fa6f70d5fa49af6d5e15cc1f3bb0d0f5342/src/Trace/ThreadTrace.cpp#L229-L233

Happen when running Lulesh.

It is because the call instruction uses global alias or bit cast, e.g.,
```
@_ZN6DomainD1Ev = dso_local unnamed_addr alias void (%class.Domain*), void (%class.Domain*)* @_ZN6DomainD2Ev
```
so,
```
callInst->getCalledFunction() == nullptr
```

2021-08-11 20:49 UTC, BradSwain requested changes

2021-08-11 20:49 UTC, BradSwain commented on src/IR/Builder.cpp
>          }
Can this be combined into a single condition?

```suggestion
        if (calledFunc == nullptr || calledFunc->isIntrinsic() || calledFunc->isDebugInfoForProfiling()) {
          continue;
        }
```

2021-08-11 20:49 UTC, BradSwain commented on src/IR/Builder.cpp
> +llvm::Function *FunctionSummaryBuilder::resolveTargetFunction(const llvm::CallBase *callInst) {
This function makes sense to me, but I dont think this is the right place for this logic.

Does it make more sense to put this logic inside of `CallIR::getCalledFunction`?

2021-08-11 20:55 UTC, bz-liu commented on src/IR/Builder.cpp
>          }
yes, just want to make sure if it is ok if we ignore when 
```calledFunc->isIntrinsic() || calledFunc->isDebugInfoForProfiling()```

2021-08-12 16:07 UTC, bz-liu commented on src/IR/Builder.cpp
> +llvm::Function *FunctionSummaryBuilder::resolveTargetFunction(const llvm::CallBase *callInst) {
we need this logic at two places:
1. https://github.com/coderrect-inc/OpenRace/blob/df3c55ea0304d95b3c21d67c7a8d8fc3cafb3615/src/IR/Builder.cpp#L143

2. https://github.com/coderrect-inc/OpenRace/blob/df3c55ea0304d95b3c21d67c7a8d8fc3cafb3615/src/Trace/ThreadTrace.cpp#L227

At the 1st use, we only have `llvm::Instruction`, do not have `CallIR` yet. Maybe move this logic to `IR.cpp` as a static function?

2021-08-12 16:47 UTC, BradSwain commented on src/IR/Builder.cpp
> +llvm::Function *FunctionSummaryBuilder::resolveTargetFunction(const llvm::CallBase *callInst) {
Yeah, I think moving the static function to CallIR makes sense.

2021-08-12 16:48 UTC, BradSwain approved these changes

2021-08-12 16:48 UTC, merged