Replace TraceBuildState with Runtime Models
coderrect-inc/OpenRace pull request #323
Opened 2021-09-14 19:22 UTC by BradSwain

The `TraceBuildState` only contain OpenMP logic (for now) and it is already becoming cluttered and leading to some bugs.

This PR replaces the "global" instance of state with separate runtime models. Logic for different runtimes (e.g. OpenMP, CUDA, etc.) can be split into their own class and interact with the trace construction in a more well defined way.

2021-09-14 23:38 UTC, BradSwain commented
Only 1 test case is failing now, DRB106.

I checked the traces and it looks like the runtime model part is correct. Only 2 tasks are being created, and both by the master thread. Not sure why the race is not being reported.

2021-09-22 04:28 UTC, funemy requested changes
Just some minor changes

2021-09-22 04:28 UTC, funemy commented on src/Trace/Build/TraceBuilder.cpp
> +bool isRecursiveThreadSpawn(const ThreadTrace &currentThread, const pta::CallGraphNodeTy *childEntry) {
Ideally we should allow the thread creation to recurse once then stop from spawning?

2021-09-22 04:28 UTC, funemy commented on src/Trace/Build/TraceBuilder.cpp
> +      // Note forkEventmpl has been moved and should not be accessed anymore
change `Note` to `NOTE:`

2021-09-24 17:10 UTC, merged