Add license checker
coderrect-inc/OpenRace pull request #89
Opened 2021-04-25 17:13 UTC by leonplust

Add GitHub Action that checks license line in each file. Because I don't know which file or directory should be excluded. I have set it to check all the .cpp and .h files in all directories. I have tested run it and below is part of the result of the test run.
<img width="741" alt="Screen Shot 2021-04-26 at 1 12 08 AM" src="https://user-images.githubusercontent.com/24830458/116002482-88deb280-a62c-11eb-901e-52df9403db7d.png">

2021-04-25 18:26 UTC, BradSwain requested changes

2021-04-25 18:26 UTC, BradSwain commented on .licenserc.json
> +    "**/*.{h, cpp}": [
Can you ignore the `examples` and `tests/data` directories?

2021-04-25 18:28 UTC, BradSwain commented
Looks great!
I think the `examples` and `tests/data` directories are the only ones we want to ignore.
Other than that looks good to me.

I will let @funemy also take a look to make sure I did not miss anything.

2021-04-26 03:47 UTC, leonplust commented
I have made the changes to ignore tests/data and examples/. Now all the files are passing the license check.

2021-04-26 03:48 UTC, leonplust commented
I have made the changes to ignore tests/data and examples/. Now all the files are passing the license check.

2021-04-26 03:57 UTC, funemy commented
The change looks good to me in general.

Just to make sure, do we also want license for files like Dockerfile and those pthread test cases (those created by us)?
If not I think this PR is ready to go @BradSwain

2021-04-26 14:17 UTC, BradSwain commented
@funemy I think only the core race detection code and test case logic needs to include the license header, but I will check and we and we can update it later.

@leonplust Thank you for your contribution! I will merge the change.

2021-04-26 14:17 UTC, BradSwain approved these changes

2021-04-26 14:19 UTC, merged

2021-04-26 14:21 UTC, funemy commented
@BradSwain ok, in that case I think the checker is added correctly.

@leonplust Thanks for the contribution, this is a neat PR.

2021-04-26 15:27 UTC, leonplust commented
You are welcome! I'm glad that I can help!